"""add_is_superadmin_to_users

Revision ID: 20250902_add_is_superadmin_to_users
Revises:  20250902_add_is_admin
Create Date: 2025-09-02 19:55:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20250902_add_is_superadmin_to_users'
down_revision = '20250902_add_is_admin'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_superadmin', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_superadmin')
    # ### end Alembic commands ###