"""add is_deleted and deleted_at columns

Revision ID: 20250909_add_is_deleted
Revises: 68bf9bce
Create Date: 2025-09-09 14:07:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20250909_add_is_deleted'
down_revision: Union[str, None] = '68bf9bce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add is_deleted column to users table
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='0'))
    # Add deleted_at column to users table  
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove deleted_at column from users table
    op.drop_column('users', 'deleted_at')
    # Remove is_deleted column from users table
    op.drop_column('users', 'is_deleted')
    # ### end Alembic commands ###