"""complete_migration

Revision ID: 227397c72889
Revises: 
Create Date: 2025-09-09 10:25:51.595461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '227397c72889'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('type', sa.Enum('challenge_deleted', 'creator_delegated', 'review_created', 'review_updated', 'refund_succeeded', 'refund_failed', 'point_awarded', 'notice_posted', 'join_completed', 'payment_reminder', 'participation_removed', name='notification_type_enum'), nullable=True))
    op.drop_index('ix_notification_event', table_name='notifications')
    op.drop_index('ix_notification_target', table_name='notifications')
    op.drop_column('notifications', 'target_type')
    op.drop_column('notifications', 'target_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('target_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('target_type', mysql.VARCHAR(length=30), nullable=True))
    op.create_index('ix_notification_target', 'notifications', ['target_type', 'target_id'], unique=False)
    op.create_index('ix_notification_event', 'notifications', ['event_type'], unique=False)
    op.drop_column('notifications', 'type')
    # ### end Alembic commands ###
