"""변경사항 설명

Revision ID: 3aa1149d06f0
Revises: f6fcb2a96ef7
Create Date: 2025-08-26 01:38:17.366605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aa1149d06f0'
down_revision: Union[str, Sequence[str], None] = 'f6fcb2a96ef7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_payment_participation', 'payments', 'participations', ['user_id', 'challenge_id'], ['user_id', 'challenge_id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_payment_participation', 'payments', type_='foreignkey')
    # ### end Alembic commands ###
