"""addround

Revision ID: 4b11e1acd33e
Revises: 7230f7f48462
Create Date: 2025-08-12 13:16:28.272206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4b11e1acd33e'
down_revision: Union[str, Sequence[str], None] = '7230f7f48462'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('challenge_rounds', 'round',
               existing_type=mysql.INTEGER(),
               comment='회차 번호(1,2,3,...)',
               existing_comment='회차 번호',
               existing_nullable=False)
    op.alter_column('challenge_rounds', 'processing_at',
               existing_type=sa.DATE(),
               comment='라운드 진행 날짜(YYYY-MM-DD)',
               existing_comment='진행 날짜',
               existing_nullable=True)
    op.alter_column('challenge_rounds', 'url',
               existing_type=mysql.TEXT(),
               comment='안내/참고 URL',
               existing_comment='온라인 링크',
               existing_nullable=True)
    op.create_index('ix_round_challenge_round', 'challenge_rounds', ['challenge_id', 'round'], unique=False)
    op.create_index('ix_round_mode', 'challenge_rounds', ['mode'], unique=False)
    op.create_index('ix_round_processing', 'challenge_rounds', ['processing_at'], unique=False)
    op.create_unique_constraint('uq_challenge_roundnum', 'challenge_rounds', ['challenge_id', 'round'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_challenge_roundnum', 'challenge_rounds', type_='unique')
    op.drop_index('ix_round_processing', table_name='challenge_rounds')
    op.drop_index('ix_round_mode', table_name='challenge_rounds')
    op.drop_index('ix_round_challenge_round', table_name='challenge_rounds')
    op.alter_column('challenge_rounds', 'url',
               existing_type=mysql.TEXT(),
               comment='온라인 링크',
               existing_comment='안내/참고 URL',
               existing_nullable=True)
    op.alter_column('challenge_rounds', 'processing_at',
               existing_type=sa.DATE(),
               comment='진행 날짜',
               existing_comment='라운드 진행 날짜(YYYY-MM-DD)',
               existing_nullable=True)
    op.alter_column('challenge_rounds', 'round',
               existing_type=mysql.INTEGER(),
               comment='회차 번호',
               existing_comment='회차 번호(1,2,3,...)',
               existing_nullable=False)
    # ### end Alembic commands ###
