"""add is_superadmin column

Revision ID: 68bf9bce
Revises: 20250904_chat_dm_nullable
Create Date: 2025-09-09 12:15:26.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68bf9bce'
down_revision: Union[str, None] = '20250904_chat_dm_nullable'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add is_superadmin column to users table
    op.add_column('users', sa.Column('is_superadmin', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove is_superadmin column from users table
    op.drop_column('users', 'is_superadmin')
    # ### end Alembic commands ###