"""init

Revision ID: 6b9cbe28680e
Revises: 
Create Date: 2025-09-08 01:55:11.993467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b9cbe28680e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=255), nullable=False),
    sa.Column('icon_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('embedding_updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag')
    )
    op.create_index('ix_tag_active', 'tags', ['is_active'], unique=False)
    op.create_index('ix_tag_text', 'tags', ['tag'], unique=False)
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('phone_encrypted', sa.String(length=255), nullable=True),
    sa.Column('phone_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('identification_number', sa.String(length=255), nullable=True),
    sa.Column('identification_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='gender_enum'), server_default='other', nullable=False),
    sa.Column('region_living', sa.String(length=50), server_default='', nullable=False),
    sa.Column('region_active', sa.String(length=50), server_default='', nullable=False),
    sa.Column('profile_image', sa.String(length=255), server_default='', nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=True),
    sa.Column('provider_id', sa.String(length=128), nullable=True),
    sa.Column('birth_year', sa.String(length=10), nullable=True),
    sa.Column('introduction', sa.Text(), nullable=False),
    sa.Column('manner_score', sa.Float(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('penalty_total', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('token_version', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_id', name='uq_user_provider_pid')
    )
    op.create_index('idx_user_active_points', 'users', ['is_active', 'total_points'], unique=False)
    op.create_index('idx_user_email_active', 'users', ['email', 'is_active'], unique=False)
    op.create_index('idx_user_region_manner', 'users', ['region_active', 'manner_score'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_email_verified'), 'users', ['email_verified'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_identification_fingerprint'), 'users', ['identification_fingerprint'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_users_manner_score'), 'users', ['manner_score'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_phone_fingerprint'), 'users', ['phone_fingerprint'], unique=True)
    op.create_index(op.f('ix_users_provider'), 'users', ['provider'], unique=False)
    op.create_index(op.f('ix_users_provider_id'), 'users', ['provider_id'], unique=False)
    op.create_index(op.f('ix_users_region_active'), 'users', ['region_active'], unique=False)
    op.create_index(op.f('ix_users_total_points'), 'users', ['total_points'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('admin_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_audit_logs_user_id'), 'admin_audit_logs', ['user_id'], unique=False)
    op.create_table('admin_notices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True, comment='작성한 관리자 ID'),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_admin_notice_active', 'admin_notices', ['is_active'], unique=False)
    op.create_index('ix_admin_notice_author', 'admin_notices', ['author_id'], unique=False)
    op.create_index('ix_admin_notice_updated', 'admin_notices', ['updated_at'], unique=False)
    op.create_index(op.f('ix_admin_notices_id'), 'admin_notices', ['id'], unique=False)
    op.create_table('admin_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'revoked', name='admin_request_status'), server_default='pending', nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_requests_user_id'), 'admin_requests', ['user_id'], unique=False)
    op.create_table('challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'recruiting', 'active', 'completed', 'cancelled', 'closed', name='challenge_status_enum'), nullable=False),
    sa.Column('min_participants', sa.Integer(), nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('current_participants', sa.Integer(), nullable=False),
    sa.Column('payment_type', sa.Enum('free', 'entry_fee', 'monthly_fee', 'both', name='payment_type_enum'), nullable=False),
    sa.Column('entry_fee', sa.Integer(), nullable=False, comment='원'),
    sa.Column('monthly_fee', sa.Integer(), nullable=False, comment='원'),
    sa.Column('mode', sa.Enum('online', 'offline', 'hybrid', name='challenge_mode_enum'), nullable=False),
    sa.Column('total_rounds', sa.Integer(), nullable=True),
    sa.Column('min_participation_rate', sa.Integer(), nullable=False, comment='%'),
    sa.Column('default_zoom_link', sa.Text(), nullable=True),
    sa.Column('default_place_name', sa.String(length=200), nullable=True),
    sa.Column('default_address', sa.String(length=300), nullable=True),
    sa.Column('default_latitude', sa.Float(), nullable=True),
    sa.Column('default_longitude', sa.Float(), nullable=True),
    sa.Column('same_place_for_all_rounds', sa.Boolean(), nullable=False),
    sa.Column('default_map_url', sa.String(length=512), nullable=True),
    sa.Column('use_reward', sa.Boolean(), nullable=False),
    sa.Column('reward_description', sa.Text(), nullable=True),
    sa.Column('cover_image_url', sa.Text(), nullable=True),
    sa.Column('require_approval', sa.Boolean(), nullable=True, comment='참가 승인 필요'),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('is_settlement_completed', sa.Boolean(), nullable=True),
    sa.Column('settlement_completed_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('current_participants >= 0', name='ck_challenge_current_participants_positive'),
    sa.CheckConstraint('end_date >= start_date', name='ck_challenge_date_range_valid'),
    sa.CheckConstraint('entry_fee >= 0', name='ck_challenge_entry_fee_positive'),
    sa.CheckConstraint('max_participants IS NULL OR max_participants >= min_participants', name='ck_challenge_max_participants_valid'),
    sa.CheckConstraint('min_participants > 0', name='ck_challenge_min_participants_positive'),
    sa.CheckConstraint('min_participation_rate >= 0 AND min_participation_rate <= 100', name='ck_challenge_participation_rate_range'),
    sa.CheckConstraint('monthly_fee >= 0', name='ck_challenge_monthly_fee_positive'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_challenge_creator_status', 'challenges', ['creator_id', 'status'], unique=False)
    op.create_index('ix_challenge_participants', 'challenges', ['current_participants', 'max_participants'], unique=False)
    op.create_index('ix_challenge_payment_type', 'challenges', ['payment_type'], unique=False)
    op.create_index('ix_challenge_public', 'challenges', ['is_public', 'is_deleted'], unique=False)
    op.create_index('ix_challenge_status_date', 'challenges', ['status', 'start_date'], unique=False)
    op.create_index(op.f('ix_challenges_creator_id'), 'challenges', ['creator_id'], unique=False)
    op.create_index(op.f('ix_challenges_end_date'), 'challenges', ['end_date'], unique=False)
    op.create_index(op.f('ix_challenges_id'), 'challenges', ['id'], unique=False)
    op.create_index(op.f('ix_challenges_start_date'), 'challenges', ['start_date'], unique=False)
    op.create_index(op.f('ix_challenges_status'), 'challenges', ['status'], unique=False)
    op.create_index(op.f('ix_challenges_title'), 'challenges', ['title'], unique=False)
    op.create_table('email_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('sent_to', sa.String(length=120), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verifications_token'), 'email_verifications', ['token'], unique=True)
    op.create_index(op.f('ix_email_verifications_user_id'), 'email_verifications', ['user_id'], unique=False)
    op.create_table('followings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('following_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'following_id', name='uq_follow_pair')
    )
    op.create_index('ix_follow_created', 'followings', ['created_at'], unique=False)
    op.create_index('ix_follow_follower', 'followings', ['follower_id'], unique=False)
    op.create_index('ix_follow_following', 'followings', ['following_id'], unique=False)
    op.create_index(op.f('ix_followings_id'), 'followings', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('event_type', sa.Enum('challenge_deleted', 'creator_delegated', 'review_created', 'review_updated', 'refund_succeeded', 'refund_failed', 'point_awarded', 'notice_posted', 'join_completed', 'payment_reminder', 'participation_removed', name='notification_event_enum'), nullable=True),
    sa.Column('type', sa.Enum('challenge_deleted', 'creator_delegated', 'review_created', 'review_updated', 'refund_succeeded', 'refund_failed', 'point_awarded', 'notice_posted', 'join_completed', 'payment_reminder', 'participation_removed', name='notification_type_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notification_created', 'notifications', ['created_at'], unique=False)
    op.create_index('ix_notification_is_read', 'notifications', ['is_read'], unique=False)
    op.create_index('ix_notification_user', 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notification_user_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('payment_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.Enum('card', 'bank_transfer', 'toss_pay', 'kakao_pay', 'point', name='payment_method_type_enum'), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_methods_id'), 'payment_methods', ['id'], unique=False)
    op.create_index(op.f('ix_payment_methods_user_id'), 'payment_methods', ['user_id'], unique=False)
    op.create_table('point_withdrawals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('point_amount', sa.Integer(), nullable=False),
    sa.Column('withdrawal_amount', sa.Integer(), nullable=False),
    sa.Column('fee_amount', sa.Integer(), nullable=False),
    sa.Column('method', sa.Enum('bank_transfer', 'toss_pay', 'kakao_pay', name='withdrawal_method_enum'), nullable=False),
    sa.Column('bank_name', sa.String(length=50), nullable=True),
    sa.Column('account_number', sa.String(length=100), nullable=True),
    sa.Column('account_holder', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('pending', 'reviewing', 'approved', 'completed', 'rejected', 'cancelled', name='withdrawal_status_enum'), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('admin_memo', sa.Text(), nullable=True),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('fee_amount >= 0', name='ck_fee_amount_positive'),
    sa.CheckConstraint('point_amount >= 10000', name='ck_withdrawal_min_points'),
    sa.CheckConstraint('withdrawal_amount > 0', name='ck_withdrawal_amount_positive'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_point_withdrawals_id'), 'point_withdrawals', ['id'], unique=False)
    op.create_index('ix_withdrawal_status_date', 'point_withdrawals', ['status', 'requested_at'], unique=False)
    op.create_index('ix_withdrawal_user_status', 'point_withdrawals', ['user_id', 'status'], unique=False)
    op.create_table('user_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('selected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag_id', 'user_id', name='uq_user_tag_pair')
    )
    op.create_index('ix_user_tag_tag', 'user_tags', ['tag_id'], unique=False)
    op.create_index('ix_user_tag_user', 'user_tags', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_tags_id'), 'user_tags', ['id'], unique=False)
    op.create_table('challenge_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_id', 'model_name', name='uq_challenge_embedding_per_model')
    )
    op.create_index(op.f('ix_challenge_embeddings_id'), 'challenge_embeddings', ['id'], unique=False)
    op.create_index('ix_embedding_challenge', 'challenge_embeddings', ['challenge_id'], unique=False)
    op.create_index('ix_embedding_model', 'challenge_embeddings', ['model_name'], unique=False)
    op.create_index('ix_embedding_updated', 'challenge_embeddings', ['updated_at'], unique=False)
    op.create_table('challenge_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.Enum('online', 'offline', name='round_mode_enum'), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False, comment='회차 번호(1,2,3,...)'),
    sa.Column('processing_at', sa.Date(), nullable=False, comment='라운드 진행 날짜'),
    sa.Column('start_time', sa.Time(), nullable=False, comment='시작 시간'),
    sa.Column('finish_time', sa.Time(), nullable=False, comment='종료 시간'),
    sa.Column('description', sa.Text(), nullable=False, comment='회차 설명'),
    sa.Column('url', sa.Text(), nullable=True, comment='안내/참고 URL'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=True, comment='위도'),
    sa.Column('lon', sa.Numeric(precision=9, scale=6), nullable=True, comment='경도'),
    sa.Column('geofence_radius_m', sa.Float(), nullable=True, comment='지오펜스 반경 (미터)'),
    sa.Column('place_name', sa.String(length=100), nullable=True, comment='장소명'),
    sa.Column('road_address', sa.String(length=255), nullable=True, comment='도로명 주소'),
    sa.Column('map_url', sa.Text(), nullable=True, comment='네이버 지도 링크(참여자 노출용)'),
    sa.Column('zoom_meeting_id', sa.String(length=255), nullable=True, comment='줌 미팅 ID'),
    sa.Column('address', sa.String(length=255), nullable=True, comment='지번 주소'),
    sa.Column('reward_enabled', sa.Boolean(), nullable=False, comment='리워드 사용 여부'),
    sa.Column('reward_text', sa.Text(), nullable=True, comment='회차 리워드 내용'),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_id', 'round', name='uq_challenge_roundnum'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_challenge_rounds_id'), 'challenge_rounds', ['id'], unique=False)
    op.create_index('ix_round_challenge_round', 'challenge_rounds', ['challenge_id', 'round'], unique=False)
    op.create_index('ix_round_mode', 'challenge_rounds', ['mode'], unique=False)
    op.create_index('ix_round_processing', 'challenge_rounds', ['processing_at'], unique=False)
    op.create_table('challenge_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('selected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag_id', 'challenge_id', name='uq_challenge_tag_pair')
    )
    op.create_index('ix_ch_tag_challenge', 'challenge_tags', ['challenge_id'], unique=False)
    op.create_index('ix_ch_tag_tag', 'challenge_tags', ['tag_id'], unique=False)
    op.create_index(op.f('ix_challenge_tags_id'), 'challenge_tags', ['id'], unique=False)
    op.create_table('chat_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_rooms_id'), 'chat_rooms', ['id'], unique=False)
    op.create_index('ix_chatroom_challenge', 'chat_rooms', ['challenge_id'], unique=False)
    op.create_index('ix_chatroom_created', 'chat_rooms', ['created_at'], unique=False)
    op.create_index('ix_chatroom_creator', 'chat_rooms', ['creator_id'], unique=False)
    op.create_table('invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('inviter_id', sa.Integer(), nullable=False),
    sa.Column('invitee_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'declined', 'canceled', name='invitation_status_enum'), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invitee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_id', 'invitee_id', name='uq_invitation_challenge_invitee')
    )
    op.create_index('ix_invitation_challenge', 'invitations', ['challenge_id'], unique=False)
    op.create_index('ix_invitation_invitee', 'invitations', ['invitee_id'], unique=False)
    op.create_index('ix_invitation_inviter', 'invitations', ['inviter_id'], unique=False)
    op.create_index('ix_invitation_reviewed', 'invitations', ['reviewed_at'], unique=False)
    op.create_index('ix_invitation_status', 'invitations', ['status'], unique=False)
    op.create_index(op.f('ix_invitations_id'), 'invitations', ['id'], unique=False)
    op.create_table('participations',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('creator', 'participant', 'manager', 'moderator', name='participation_role_enum'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'payment_pending', 'active', 'paused', 'completed', 'cancelled', 'expelled', 'payment_failed', name='participation_status_enum'), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False, comment='참가 신청 시간'),
    sa.Column('activated_at', sa.DateTime(), nullable=True, comment='실제 참가 시작 시간 (결제 완료 후)'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='완료 시간'),
    sa.Column('left_at', sa.DateTime(), nullable=True, comment='탈퇴 시간'),
    sa.Column('payment_cycle', sa.Enum('entry_fee', 'monthly', 'free', name='payment_cycle_enum'), nullable=True, comment='선택한 결제 방식 (챌린지가 multiple 옵션일 때)'),
    sa.Column('next_payment_date', sa.Date(), nullable=True, comment='다음 결제 예정일 (월회비용)'),
    sa.Column('payment_failed_count', sa.Integer(), nullable=False, comment='연속 결제 실패 횟수'),
    sa.Column('total_paid_amount', sa.Integer(), nullable=False, comment='총 결제 금액'),
    sa.Column('progress_rate', sa.Float(), nullable=False, comment='진행률 (0-100%)'),
    sa.Column('attendance_count', sa.Integer(), nullable=False, comment='총 출석 횟수'),
    sa.Column('total_rounds', sa.Integer(), nullable=True, comment='참가한 시점의 총 회차 수 (변경 추적용)'),
    sa.Column('leave_type', sa.Enum('voluntary', 'kicked', 'payment_failure', 'rule_violation', 'inactivity', name='leave_type_enum'), nullable=True, comment='탈퇴 사유'),
    sa.Column('leave_reason', sa.Text(), nullable=True, comment='상세 탈퇴 사유'),
    sa.Column('kicked_by', sa.Integer(), nullable=True, comment='퇴출 처리한 관리자 ID'),
    sa.Column('is_notification_enabled', sa.Boolean(), nullable=False, comment='알림 수신 여부'),
    sa.Column('auto_payment_enabled', sa.Boolean(), nullable=False, comment='자동 결제 활성화 여부'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='참여 레코드 활성 여부 (호환용)'),
    sa.Column('join_motivation', sa.Text(), nullable=True, comment='참가 동기/목표'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('attendance_count >= 0', name='ck_participation_attendance_positive'),
    sa.CheckConstraint('payment_failed_count >= 0', name='ck_participation_payment_failed_positive'),
    sa.CheckConstraint('progress_rate >= 0 AND progress_rate <= 100', name='ck_participation_progress_range'),
    sa.CheckConstraint('total_paid_amount >= 0', name='ck_participation_total_paid_positive'),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.ForeignKeyConstraint(['kicked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'challenge_id'),
    sa.UniqueConstraint('user_id', 'challenge_id', name='uq_participation_user_challenge')
    )
    op.create_index('ix_participation_challenge', 'participations', ['challenge_id'], unique=False)
    op.create_index('ix_participation_joined_status', 'participations', ['joined_at', 'status'], unique=False)
    op.create_index('ix_participation_next_payment', 'participations', ['next_payment_date'], unique=False)
    op.create_index('ix_participation_progress', 'participations', ['progress_rate'], unique=False)
    op.create_index('ix_participation_status_role', 'participations', ['status', 'role'], unique=False)
    op.create_index('ix_participation_user', 'participations', ['user_id'], unique=False)
    op.create_index(op.f('ix_participations_joined_at'), 'participations', ['joined_at'], unique=False)
    op.create_index(op.f('ix_participations_next_payment_date'), 'participations', ['next_payment_date'], unique=False)
    op.create_index(op.f('ix_participations_role'), 'participations', ['role'], unique=False)
    op.create_index(op.f('ix_participations_status'), 'participations', ['status'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=True),
    sa.Column('method', sa.Enum('card', 'bank_transfer', 'toss_pay', 'kakao_pay', 'point', name='payment_method_type_enum'), nullable=False),
    sa.Column('transaction_type', sa.Enum('entry_fee', 'monthly_fee', 'penalty', 'etc', name='payment_transaction_type_enum'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'success', 'completed', 'failed', 'cancelled', 'refunded', 'partial_refunded', name='payment_status_enum'), nullable=False),
    sa.Column('order_id', sa.String(length=100), nullable=False),
    sa.Column('order_name', sa.String(length=200), nullable=True),
    sa.Column('payment_key', sa.String(length=255), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('failure_code', sa.String(length=50), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_payment_amount_positive'),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.ForeignKeyConstraint(['user_id', 'challenge_id'], ['participations.user_id', 'participations.challenge_id'], name='fk_payment_participation', use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_key')
    )
    op.create_index('ix_payment_challenge_type', 'payments', ['challenge_id', 'transaction_type'], unique=False)
    op.create_index('ix_payment_user_status', 'payments', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_payments_challenge_id'), 'payments', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=True)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_table('penalty_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.Enum('bad_language', 'report', 'frequent_kick', 'frequent_leave', name='penalty_source_enum'), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('given_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_penalty_challenge', 'penalty_histories', ['challenge_id'], unique=False)
    op.create_index('ix_penalty_given_at', 'penalty_histories', ['given_at'], unique=False)
    op.create_index(op.f('ix_penalty_histories_id'), 'penalty_histories', ['id'], unique=False)
    op.create_index('ix_penalty_score', 'penalty_histories', ['score'], unique=False)
    op.create_index('ix_penalty_source', 'penalty_histories', ['source_type'], unique=False)
    op.create_index('ix_penalty_user', 'penalty_histories', ['user_id'], unique=False)
    op.create_table('point_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('point_amount', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('gain', 'use', 'refund', 'challenge_reward', 'withdrawal', name='point_history_type_enum'), nullable=False),
    sa.Column('total_earned_point', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ph_amount', 'point_histories', ['point_amount'], unique=False)
    op.create_index('ix_ph_challenge', 'point_histories', ['challenge_id'], unique=False)
    op.create_index('ix_ph_type', 'point_histories', ['type'], unique=False)
    op.create_index('ix_ph_user_created', 'point_histories', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_point_histories_id'), 'point_histories', ['id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('reported_id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'under_review', 'resolved', 'rejected', 'cancelled', name='report_status_enum'), nullable=False),
    sa.Column('is_false_report', sa.Boolean(), nullable=False),
    sa.Column('penalty_given', sa.Boolean(), nullable=False),
    sa.Column('penalty_score', sa.Integer(), nullable=False),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reported_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_report_challenge', 'reports', ['challenge_id'], unique=False)
    op.create_index('ix_report_created', 'reports', ['created_at'], unique=False)
    op.create_index('ix_report_reported', 'reports', ['reported_id'], unique=False)
    op.create_index('ix_report_reporter', 'reports', ['reporter_id'], unique=False)
    op.create_index('ix_report_status', 'reports', ['status'], unique=False)
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('file_url', sa.String(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_index('ix_chatmsg_is_read', 'chat_messages', ['is_read'], unique=False)
    op.create_index('ix_chatmsg_room_created', 'chat_messages', ['room_id', 'created_at'], unique=False)
    op.create_index('ix_chatmsg_sender', 'chat_messages', ['sender_id'], unique=False)
    op.create_table('chat_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'user_id', name='uq_chat_participant')
    )
    op.create_index(op.f('ix_chat_participants_id'), 'chat_participants', ['id'], unique=False)
    op.create_index('ix_chatpart_joined', 'chat_participants', ['joined_at'], unique=False)
    op.create_index('ix_chatpart_room', 'chat_participants', ['room_id'], unique=False)
    op.create_index('ix_chatpart_user', 'chat_participants', ['user_id'], unique=False)
    op.create_table('proofs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('proof_type', sa.String(length=30), nullable=False),
    sa.Column('file_url', sa.String(length=255), nullable=True),
    sa.Column('exif_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='proof_status_enum'), nullable=False),
    sa.Column('initial_verified_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('ai_score', sa.Float(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('explanation_choices', sa.String(length=255), nullable=True),
    sa.Column('explanation_file_url', sa.String(length=255), nullable=True),
    sa.Column('files_json', sa.JSON(), nullable=True),
    sa.Column('face_compare_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['initial_verified_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['round_id'], ['challenge_rounds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_proof_challenge', 'proofs', ['challenge_id'], unique=False)
    op.create_index('ix_proof_round_user_submitted', 'proofs', ['round_id', 'user_id', 'submitted_at'], unique=False)
    op.create_index('ix_proof_status', 'proofs', ['status'], unique=False)
    op.create_index(op.f('ix_proofs_id'), 'proofs', ['id'], unique=False)
    op.create_table('qrcodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('qr_token', sa.String(length=255), nullable=False),
    sa.Column('scanned_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('jti', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('valid', 'used', 'expired', 'revoked', name='qr_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['challenge_rounds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'round_id', name='uq_qr_user_round')
    )
    op.create_index('ix_qr_round_status', 'qrcodes', ['round_id', 'status'], unique=False)
    op.create_index('ix_qr_token', 'qrcodes', ['qr_token'], unique=False)
    op.create_index('ix_qr_user', 'qrcodes', ['user_id'], unique=False)
    op.create_index(op.f('ix_qrcodes_id'), 'qrcodes', ['id'], unique=False)
    op.create_table('refunds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=True),
    sa.Column('refund_amount', sa.Integer(), nullable=False),
    sa.Column('refund_reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'success', 'completed', 'failed', 'cancelled', 'refunded', 'partial_refunded', name='refund_status_enum'), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('refund_amount >= 0', name='ck_refund_amount_positive'),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_refund_user_date', 'refunds', ['user_id', 'requested_at'], unique=False)
    op.create_index(op.f('ix_refunds_challenge_id'), 'refunds', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_refunds_id'), 'refunds', ['id'], unique=False)
    op.create_index(op.f('ix_refunds_payment_id'), 'refunds', ['payment_id'], unique=False)
    op.create_index(op.f('ix_refunds_user_id'), 'refunds', ['user_id'], unique=False)
    op.create_table('report_proofs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_proofs_id'), 'report_proofs', ['id'], unique=False)
    op.create_index('ix_reportproof_report', 'report_proofs', ['report_id'], unique=False)
    op.create_index('ix_reportproof_uploaded', 'report_proofs', ['uploaded_at'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('helpful_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('visible', 'hidden', 'deleted', name='review_status_enum'), nullable=False),
    sa.Column('images_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['round_id'], ['challenge_rounds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'challenge_id', name='uq_review_user_challenge'),
    sa.UniqueConstraint('user_id', 'round_id', name='uq_review_user_round')
    )
    op.create_index('ix_review_challenge', 'reviews', ['challenge_id'], unique=False)
    op.create_index('ix_review_helpful_count', 'reviews', ['helpful_count'], unique=False)
    op.create_index('ix_review_rating', 'reviews', ['rating'], unique=False)
    op.create_index('ix_review_round', 'reviews', ['round_id'], unique=False)
    op.create_index('ix_review_status', 'reviews', ['status'], unique=False)
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_table('round_managers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['round_id'], ['challenge_rounds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_id', 'round_id', name='uq_round_manager_one_per_round')
    )
    op.create_index('ix_rm_ch_round', 'round_managers', ['challenge_id', 'round_id'], unique=False)
    op.create_index('ix_rm_user', 'round_managers', ['user_id'], unique=False)
    op.create_table('round_pictures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('file_url', sa.String(length=255), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['challenge_rounds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_round_pictures_id'), 'round_pictures', ['id'], unique=False)
    op.create_index('ix_roundpic_created', 'round_pictures', ['created_at'], unique=False)
    op.create_index('ix_roundpic_public', 'round_pictures', ['is_public'], unique=False)
    op.create_index('ix_roundpic_round', 'round_pictures', ['round_id'], unique=False)
    op.create_index('ix_roundpic_uploader', 'round_pictures', ['uploaded_by'], unique=False)
    op.create_table('review_helpfuls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id', 'user_id', name='uq_helpful_review_user')
    )
    op.create_index('ix_helpful_created', 'review_helpfuls', ['created_at'], unique=False)
    op.create_index('ix_helpful_review', 'review_helpfuls', ['review_id'], unique=False)
    op.create_index('ix_helpful_user', 'review_helpfuls', ['user_id'], unique=False)
    op.create_index(op.f('ix_review_helpfuls_id'), 'review_helpfuls', ['id'], unique=False)
    op.create_table('round_attendances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('is_checked_in', sa.Boolean(), nullable=False),
    sa.Column('is_checked_out', sa.Boolean(), nullable=False),
    sa.Column('checkin_time', sa.DateTime(), nullable=True),
    sa.Column('checkout_time', sa.DateTime(), nullable=True),
    sa.Column('manually_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('ai_score', sa.Float(), nullable=True),
    sa.Column('qr_id', sa.Integer(), nullable=True),
    sa.Column('scanned_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'present', 'late', 'absent', 'rejected', name='attendance_status_enum'), nullable=False),
    sa.Column('proof_id', sa.Integer(), nullable=True),
    sa.Column('verified_by_meta', sa.Boolean(), nullable=False),
    sa.Column('meta_check_time', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('check_method', sa.Enum('qr', 'gps', 'image', 'manual', name='check_method_enum'), nullable=False),
    sa.Column('auto_decision', sa.Enum('_pass', 'review', 'fail', name='auto_decision_enum'), nullable=True),
    sa.Column('initial_decision', sa.Enum('approved', 'rejected', 'review', name='initial_decision_enum'), nullable=False),
    sa.Column('initial_decision_reason', sa.Text(), nullable=True),
    sa.Column('initial_decision_code', sa.Enum('late', 'no_gps', 'wrong_place', 'no_face', 'file_invalid', 'other', name='initial_decision_code_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['proof_id'], ['proofs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['qr_id'], ['qrcodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['round_id'], ['challenge_rounds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'round_id', name='uq_ra_user_round')
    )
    op.create_index('ix_ra_checkin', 'round_attendances', ['checkin_time'], unique=False)
    op.create_index('ix_ra_round_user', 'round_attendances', ['round_id', 'user_id'], unique=False)
    op.create_index('ix_ra_status', 'round_attendances', ['status'], unique=False)
    op.create_index(op.f('ix_round_attendances_id'), 'round_attendances', ['id'], unique=False)
    op.create_table('appeals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_attendance_id', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('files_url', sa.JSON(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('appeal_status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('decision_code', sa.Enum('insufficient_evidence', 'still_no_gps', 'time_mismatch', 'face_mismatch', 'duplicate', 'other', name='appeal_decision_code_enum'), nullable=True),
    sa.Column('auto_reason', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['round_attendance_id'], ['round_attendances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_appeal_ra', 'appeals', ['round_attendance_id'], unique=False)
    op.create_index('ix_appeal_status', 'appeals', ['appeal_status'], unique=False)
    op.create_index('ix_appeal_submitted', 'appeals', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_appeals_id'), 'appeals', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appeals_id'), table_name='appeals')
    op.drop_index('ix_appeal_submitted', table_name='appeals')
    op.drop_index('ix_appeal_status', table_name='appeals')
    op.drop_index('ix_appeal_ra', table_name='appeals')
    op.drop_table('appeals')
    op.drop_index(op.f('ix_round_attendances_id'), table_name='round_attendances')
    op.drop_index('ix_ra_status', table_name='round_attendances')
    op.drop_index('ix_ra_round_user', table_name='round_attendances')
    op.drop_index('ix_ra_checkin', table_name='round_attendances')
    op.drop_table('round_attendances')
    op.drop_index(op.f('ix_review_helpfuls_id'), table_name='review_helpfuls')
    op.drop_index('ix_helpful_user', table_name='review_helpfuls')
    op.drop_index('ix_helpful_review', table_name='review_helpfuls')
    op.drop_index('ix_helpful_created', table_name='review_helpfuls')
    op.drop_table('review_helpfuls')
    op.drop_index('ix_roundpic_uploader', table_name='round_pictures')
    op.drop_index('ix_roundpic_round', table_name='round_pictures')
    op.drop_index('ix_roundpic_public', table_name='round_pictures')
    op.drop_index('ix_roundpic_created', table_name='round_pictures')
    op.drop_index(op.f('ix_round_pictures_id'), table_name='round_pictures')
    op.drop_table('round_pictures')
    op.drop_index('ix_rm_user', table_name='round_managers')
    op.drop_index('ix_rm_ch_round', table_name='round_managers')
    op.drop_table('round_managers')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_index('ix_review_status', table_name='reviews')
    op.drop_index('ix_review_round', table_name='reviews')
    op.drop_index('ix_review_rating', table_name='reviews')
    op.drop_index('ix_review_helpful_count', table_name='reviews')
    op.drop_index('ix_review_challenge', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index('ix_reportproof_uploaded', table_name='report_proofs')
    op.drop_index('ix_reportproof_report', table_name='report_proofs')
    op.drop_index(op.f('ix_report_proofs_id'), table_name='report_proofs')
    op.drop_table('report_proofs')
    op.drop_index(op.f('ix_refunds_user_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_payment_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_challenge_id'), table_name='refunds')
    op.drop_index('ix_refund_user_date', table_name='refunds')
    op.drop_table('refunds')
    op.drop_index(op.f('ix_qrcodes_id'), table_name='qrcodes')
    op.drop_index('ix_qr_user', table_name='qrcodes')
    op.drop_index('ix_qr_token', table_name='qrcodes')
    op.drop_index('ix_qr_round_status', table_name='qrcodes')
    op.drop_table('qrcodes')
    op.drop_index(op.f('ix_proofs_id'), table_name='proofs')
    op.drop_index('ix_proof_status', table_name='proofs')
    op.drop_index('ix_proof_round_user_submitted', table_name='proofs')
    op.drop_index('ix_proof_challenge', table_name='proofs')
    op.drop_table('proofs')
    op.drop_index('ix_chatpart_user', table_name='chat_participants')
    op.drop_index('ix_chatpart_room', table_name='chat_participants')
    op.drop_index('ix_chatpart_joined', table_name='chat_participants')
    op.drop_index(op.f('ix_chat_participants_id'), table_name='chat_participants')
    op.drop_table('chat_participants')
    op.drop_index('ix_chatmsg_sender', table_name='chat_messages')
    op.drop_index('ix_chatmsg_room_created', table_name='chat_messages')
    op.drop_index('ix_chatmsg_is_read', table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_index('ix_report_status', table_name='reports')
    op.drop_index('ix_report_reporter', table_name='reports')
    op.drop_index('ix_report_reported', table_name='reports')
    op.drop_index('ix_report_created', table_name='reports')
    op.drop_index('ix_report_challenge', table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_point_histories_id'), table_name='point_histories')
    op.drop_index('ix_ph_user_created', table_name='point_histories')
    op.drop_index('ix_ph_type', table_name='point_histories')
    op.drop_index('ix_ph_challenge', table_name='point_histories')
    op.drop_index('ix_ph_amount', table_name='point_histories')
    op.drop_table('point_histories')
    op.drop_index('ix_penalty_user', table_name='penalty_histories')
    op.drop_index('ix_penalty_source', table_name='penalty_histories')
    op.drop_index('ix_penalty_score', table_name='penalty_histories')
    op.drop_index(op.f('ix_penalty_histories_id'), table_name='penalty_histories')
    op.drop_index('ix_penalty_given_at', table_name='penalty_histories')
    op.drop_index('ix_penalty_challenge', table_name='penalty_histories')
    op.drop_table('penalty_histories')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_challenge_id'), table_name='payments')
    op.drop_index('ix_payment_user_status', table_name='payments')
    op.drop_index('ix_payment_challenge_type', table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_participations_status'), table_name='participations')
    op.drop_index(op.f('ix_participations_role'), table_name='participations')
    op.drop_index(op.f('ix_participations_next_payment_date'), table_name='participations')
    op.drop_index(op.f('ix_participations_joined_at'), table_name='participations')
    op.drop_index('ix_participation_user', table_name='participations')
    op.drop_index('ix_participation_status_role', table_name='participations')
    op.drop_index('ix_participation_progress', table_name='participations')
    op.drop_index('ix_participation_next_payment', table_name='participations')
    op.drop_index('ix_participation_joined_status', table_name='participations')
    op.drop_index('ix_participation_challenge', table_name='participations')
    op.drop_table('participations')
    op.drop_index(op.f('ix_invitations_id'), table_name='invitations')
    op.drop_index('ix_invitation_status', table_name='invitations')
    op.drop_index('ix_invitation_reviewed', table_name='invitations')
    op.drop_index('ix_invitation_inviter', table_name='invitations')
    op.drop_index('ix_invitation_invitee', table_name='invitations')
    op.drop_index('ix_invitation_challenge', table_name='invitations')
    op.drop_table('invitations')
    op.drop_index('ix_chatroom_creator', table_name='chat_rooms')
    op.drop_index('ix_chatroom_created', table_name='chat_rooms')
    op.drop_index('ix_chatroom_challenge', table_name='chat_rooms')
    op.drop_index(op.f('ix_chat_rooms_id'), table_name='chat_rooms')
    op.drop_table('chat_rooms')
    op.drop_index(op.f('ix_challenge_tags_id'), table_name='challenge_tags')
    op.drop_index('ix_ch_tag_tag', table_name='challenge_tags')
    op.drop_index('ix_ch_tag_challenge', table_name='challenge_tags')
    op.drop_table('challenge_tags')
    op.drop_index('ix_round_processing', table_name='challenge_rounds')
    op.drop_index('ix_round_mode', table_name='challenge_rounds')
    op.drop_index('ix_round_challenge_round', table_name='challenge_rounds')
    op.drop_index(op.f('ix_challenge_rounds_id'), table_name='challenge_rounds')
    op.drop_table('challenge_rounds')
    op.drop_index('ix_embedding_updated', table_name='challenge_embeddings')
    op.drop_index('ix_embedding_model', table_name='challenge_embeddings')
    op.drop_index('ix_embedding_challenge', table_name='challenge_embeddings')
    op.drop_index(op.f('ix_challenge_embeddings_id'), table_name='challenge_embeddings')
    op.drop_table('challenge_embeddings')
    op.drop_index(op.f('ix_user_tags_id'), table_name='user_tags')
    op.drop_index('ix_user_tag_user', table_name='user_tags')
    op.drop_index('ix_user_tag_tag', table_name='user_tags')
    op.drop_table('user_tags')
    op.drop_index('ix_withdrawal_user_status', table_name='point_withdrawals')
    op.drop_index('ix_withdrawal_status_date', table_name='point_withdrawals')
    op.drop_index(op.f('ix_point_withdrawals_id'), table_name='point_withdrawals')
    op.drop_table('point_withdrawals')
    op.drop_index(op.f('ix_payment_methods_user_id'), table_name='payment_methods')
    op.drop_index(op.f('ix_payment_methods_id'), table_name='payment_methods')
    op.drop_table('payment_methods')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index('ix_notification_user_read', table_name='notifications')
    op.drop_index('ix_notification_user', table_name='notifications')
    op.drop_index('ix_notification_is_read', table_name='notifications')
    op.drop_index('ix_notification_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_followings_id'), table_name='followings')
    op.drop_index('ix_follow_following', table_name='followings')
    op.drop_index('ix_follow_follower', table_name='followings')
    op.drop_index('ix_follow_created', table_name='followings')
    op.drop_table('followings')
    op.drop_index(op.f('ix_email_verifications_user_id'), table_name='email_verifications')
    op.drop_index(op.f('ix_email_verifications_token'), table_name='email_verifications')
    op.drop_table('email_verifications')
    op.drop_index(op.f('ix_challenges_title'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_status'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_start_date'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_id'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_end_date'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_creator_id'), table_name='challenges')
    op.drop_index('ix_challenge_status_date', table_name='challenges')
    op.drop_index('ix_challenge_public', table_name='challenges')
    op.drop_index('ix_challenge_payment_type', table_name='challenges')
    op.drop_index('ix_challenge_participants', table_name='challenges')
    op.drop_index('ix_challenge_creator_status', table_name='challenges')
    op.drop_table('challenges')
    op.drop_index(op.f('ix_admin_requests_user_id'), table_name='admin_requests')
    op.drop_table('admin_requests')
    op.drop_index(op.f('ix_admin_notices_id'), table_name='admin_notices')
    op.drop_index('ix_admin_notice_updated', table_name='admin_notices')
    op.drop_index('ix_admin_notice_author', table_name='admin_notices')
    op.drop_index('ix_admin_notice_active', table_name='admin_notices')
    op.drop_table('admin_notices')
    op.drop_index(op.f('ix_admin_audit_logs_user_id'), table_name='admin_audit_logs')
    op.drop_table('admin_audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_total_points'), table_name='users')
    op.drop_index(op.f('ix_users_region_active'), table_name='users')
    op.drop_index(op.f('ix_users_provider_id'), table_name='users')
    op.drop_index(op.f('ix_users_provider'), table_name='users')
    op.drop_index(op.f('ix_users_phone_fingerprint'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_manner_score'), table_name='users')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_identification_fingerprint'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email_verified'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_user_region_manner', table_name='users')
    op.drop_index('idx_user_email_active', table_name='users')
    op.drop_index('idx_user_active_points', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_index('ix_tag_text', table_name='tags')
    op.drop_index('ix_tag_active', table_name='tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
