"""Add new notification events

Revision ID: 6ed3739a3a89
Revises: 1e78e90b0832
Create Date: 2025-09-05 05:19:38.801281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
<<<<<<< Updated upstream
=======
from sqlalchemy import inspect
>>>>>>> Stashed changes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6ed3739a3a89'
down_revision: Union[str, Sequence[str], None] = '1e78e90b0832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
<<<<<<< Updated upstream
    op.drop_index('ix_email_verifications_user_id', table_name='email_verifications')
    op.drop_table('email_verifications')
    op.drop_index('ix_point_exchange_requests_id', table_name='point_exchange_requests')
    op.drop_index('ix_px_amount', table_name='point_exchange_requests')
    op.drop_index('ix_px_status', table_name='point_exchange_requests')
    op.drop_index('ix_px_user_requested', table_name='point_exchange_requests')
    op.drop_table('point_exchange_requests')
=======
    # Drop email_verifications if it exists
    bind = op.get_bind()
    inspector = inspect(bind)
    if inspector.has_table('email_verifications'):
        # Avoid dropping indexes explicitly because MySQL may require the index
        # for the FK; dropping the table removes FKs and indexes safely.
        op.drop_table('email_verifications')
    # Drop point_exchange_requests in one shot to avoid FK/index dependency errors
    if inspector.has_table('point_exchange_requests'):
        op.drop_table('point_exchange_requests')
>>>>>>> Stashed changes
    op.alter_column('challenge_rounds', 'reward_enabled',
               existing_type=mysql.TINYINT(display_width=1),
               comment='보상 활성화 여부',
               existing_comment='리워드 사용 여부',
               existing_nullable=False)
    op.drop_column('challenge_rounds', 'reward_text')
    op.alter_column('challenges', 'title',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('challenges', 'status',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('draft', 'recruiting', 'active', 'completed', 'cancelled', 'closed', name='challenge_status_enum'),
               nullable=False,
               comment=None,
               existing_comment='챌린지 상태')
    op.alter_column('challenges', 'min_participants',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='최소 참가자 수')
    op.alter_column('challenges', 'max_participants',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='최대 참가자 수',
               existing_nullable=True)
    op.alter_column('challenges', 'payment_type',
               existing_type=mysql.ENUM('free', 'entry_fee', 'monthly_fee'),
               nullable=False,
               existing_server_default=sa.text("'free'"))
    op.alter_column('challenges', 'entry_fee',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment='원',
               existing_server_default=sa.text("'0'"))
    op.alter_column('challenges', 'monthly_fee',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment='원',
               existing_server_default=sa.text("'0'"))
    op.alter_column('challenges', 'mode',
               existing_type=mysql.ENUM('online', 'offline', 'hybrid'),
               nullable=False)
    op.alter_column('challenges', 'total_rounds',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='총 회차 수',
               existing_nullable=True)
    op.alter_column('challenges', 'min_participation_rate',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment='%',
               existing_comment='최소 참여율 (%)')
    op.alter_column('challenges', 'default_place_name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('challenges', 'default_address',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=300),
               existing_nullable=True)
    op.alter_column('challenges', 'same_place_for_all_rounds',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='모든 회차 동일 장소 여부',
               existing_nullable=False)
    op.alter_column('challenges', 'use_reward',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               comment=None,
               existing_comment='리워드 사용 여부')
    op.alter_column('challenges', 'require_approval',
               existing_type=mysql.TINYINT(display_width=1),
               comment='참가 승인 필요',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('challenges', 'is_public',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('challenges', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               comment=None,
               existing_comment='삭제 여부')
    op.alter_column('challenges', 'deleted_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='삭제 시간',
               existing_nullable=True)
    op.alter_column('challenges', 'deleted_by',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='삭제한 유저',
               existing_nullable=True)
    op.alter_column('challenges', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('challenges', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.create_index('ix_challenge_creator_status', 'challenges', ['creator_id', 'status'], unique=False)
    op.create_index('ix_challenge_participants', 'challenges', ['current_participants', 'max_participants'], unique=False)
    op.create_index('ix_challenge_payment_type', 'challenges', ['payment_type'], unique=False)
    op.create_index('ix_challenge_public', 'challenges', ['is_public', 'is_deleted'], unique=False)
    op.create_index('ix_challenge_status_date', 'challenges', ['status', 'start_date'], unique=False)
    op.create_index(op.f('ix_challenges_creator_id'), 'challenges', ['creator_id'], unique=False)
    op.create_index(op.f('ix_challenges_end_date'), 'challenges', ['end_date'], unique=False)
    op.create_index(op.f('ix_challenges_start_date'), 'challenges', ['start_date'], unique=False)
    op.create_index(op.f('ix_challenges_status'), 'challenges', ['status'], unique=False)
    op.create_index(op.f('ix_challenges_title'), 'challenges', ['title'], unique=False)
    op.drop_constraint('challenges_ibfk_3', 'challenges', type_='foreignkey')
    op.drop_column('challenges', 'default_map_url')
    op.drop_column('challenges', 'max_participation_rate')
    op.drop_column('challenges', 'fee')
    op.drop_column('challenges', 'default_road_address')
    op.drop_column('challenges', 'is_closed')
    op.drop_column('challenges', 'cover_image_url')
    op.drop_column('challenges', 'participation_fee')
    op.drop_column('challenges', 'reward')
    op.drop_column('challenges', 'cover_round_picture_id')
    op.drop_column('challenges', 'default_place_id')
    op.alter_column('participations', 'status',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('pending', 'payment_pending', 'active', 'paused', 'completed', 'cancelled', 'expelled', 'payment_failed', name='participation_status_enum'),
               existing_nullable=False)
    op.alter_column('participations', 'joined_at',
               existing_type=mysql.DATETIME(),
               comment='참가 신청 시간',
               existing_nullable=False)
    op.drop_index('ix_participation_active', table_name='participations')
    op.drop_index('ix_participation_joined', table_name='participations')
    op.drop_index('ix_participation_role', table_name='participations')
    op.drop_index('ix_participation_status', table_name='participations')
    op.drop_index('ix_participations_id', table_name='participations')
    op.create_index('ix_participation_joined_status', 'participations', ['joined_at', 'status'], unique=False)
    op.create_index('ix_participation_status_role', 'participations', ['status', 'role'], unique=False)
    op.create_index(op.f('ix_participations_is_active'), 'participations', ['is_active'], unique=False)
    op.create_index(op.f('ix_participations_joined_at'), 'participations', ['joined_at'], unique=False)
    op.create_index(op.f('ix_participations_role'), 'participations', ['role'], unique=False)
    op.create_index(op.f('ix_participations_status'), 'participations', ['status'], unique=False)
    op.drop_constraint('participations_ibfk_1', 'participations', type_='foreignkey')
    op.drop_constraint('participations_ibfk_2', 'participations', type_='foreignkey')
    op.create_foreign_key(None, 'participations', 'challenges', ['challenge_id'], ['id'])
    op.create_foreign_key(None, 'participations', 'users', ['user_id'], ['id'])
    op.drop_column('participations', 'id')
    op.drop_column('participations', 'leave_type')
    op.add_column('payments', sa.Column('method', sa.Enum('card', 'bank_transfer', 'toss_pay', 'kakao_pay', 'point', name='payment_method_type_enum'), nullable=False))
    op.add_column('payments', sa.Column('transaction_type', sa.Enum('entry_fee', 'monthly_fee', 'penalty', 'etc', name='payment_transaction_type_enum'), nullable=False))
    op.add_column('payments', sa.Column('order_id', sa.String(length=100), nullable=False))
    op.add_column('payments', sa.Column('order_name', sa.String(length=200), nullable=True))
    op.add_column('payments', sa.Column('payment_key', sa.String(length=255), nullable=True))
    op.add_column('payments', sa.Column('requested_at', sa.DateTime(), nullable=False))
    op.add_column('payments', sa.Column('approved_at', sa.DateTime(), nullable=True))
    op.add_column('payments', sa.Column('failed_at', sa.DateTime(), nullable=True))
    op.add_column('payments', sa.Column('cancelled_at', sa.DateTime(), nullable=True))
    op.add_column('payments', sa.Column('failure_code', sa.String(length=50), nullable=True))
    op.add_column('payments', sa.Column('failure_message', sa.Text(), nullable=True))
    op.add_column('payments', sa.Column('cancel_reason', sa.Text(), nullable=True))
    op.add_column('payments', sa.Column('metadata_json', sa.Text(), nullable=True))
    op.alter_column('payments', 'challenge_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('payments', 'amount',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index('ix_payment_amount', table_name='payments')
    op.drop_index('ix_payment_challenge', table_name='payments')
    op.drop_index('ix_payment_status', table_name='payments')
    op.drop_index('ix_payment_user_created', table_name='payments')
    op.drop_index('uq_payment_idem', table_name='payments')
    op.drop_index('uq_payment_toss', table_name='payments')
    op.create_index('ix_payment_challenge_type', 'payments', ['challenge_id', 'transaction_type'], unique=False)
    op.create_index('ix_payment_user_status', 'payments', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_payments_challenge_id'), 'payments', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=True)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'payments', ['payment_key'])
    op.drop_constraint('payments_ibfk_2', 'payments', type_='foreignkey')
    op.drop_constraint('payments_ibfk_1', 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'payments', 'challenges', ['challenge_id'], ['id'])
    op.create_foreign_key('fk_payment_participation', 'payments', 'participations', ['user_id', 'challenge_id'], ['user_id', 'challenge_id'], use_alter=True)
    op.drop_column('payments', 'currency')
    op.drop_column('payments', 'toss_payment_id')
    op.drop_column('payments', 'planner_id_at_payment')
    op.drop_column('payments', 'payment_type')
    op.drop_column('payments', 'idempotency_key')
    op.add_column('refunds', sa.Column('payment_id', sa.Integer(), nullable=False))
    op.add_column('refunds', sa.Column('refund_amount', sa.Integer(), nullable=False))
    op.add_column('refunds', sa.Column('refund_reason', sa.Text(), nullable=True))
    op.add_column('refunds', sa.Column('status', sa.Enum('pending', 'success', 'completed', 'failed', 'cancelled', 'refunded', 'partial_refunded', name='refund_status_enum'), nullable=False))
    op.add_column('refunds', sa.Column('requested_at', sa.DateTime(), nullable=False))
    op.alter_column('refunds', 'challenge_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_index('ix_refund_amount', table_name='refunds')
    op.drop_index('ix_refund_challenge', table_name='refunds')
    op.drop_index('ix_refund_status', table_name='refunds')
    op.drop_index('ix_refund_user_processed', table_name='refunds')
    op.drop_index('uq_refund_toss', table_name='refunds')
    op.create_index('ix_refund_user_date', 'refunds', ['user_id', 'requested_at'], unique=False)
    op.create_index(op.f('ix_refunds_challenge_id'), 'refunds', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_refunds_payment_id'), 'refunds', ['payment_id'], unique=False)
    op.create_index(op.f('ix_refunds_user_id'), 'refunds', ['user_id'], unique=False)
    op.drop_constraint('refunds_ibfk_1', 'refunds', type_='foreignkey')
    op.drop_constraint('refunds_ibfk_2', 'refunds', type_='foreignkey')
    op.create_foreign_key(None, 'refunds', 'challenges', ['challenge_id'], ['id'])
    op.create_foreign_key(None, 'refunds', 'payments', ['payment_id'], ['id'])
    op.create_foreign_key(None, 'refunds', 'users', ['user_id'], ['id'])
    op.drop_column('refunds', 'reason')
    op.drop_column('refunds', 'currency')
    op.drop_column('refunds', 'error_msg')
    op.drop_column('refunds', 'toss_refund_id')
    op.drop_column('refunds', 'amount')
    op.drop_column('refunds', 'refund_status')
    op.drop_index('idx_reviews_target_user', table_name='reviews')
    op.drop_index('uq_review_user_target_challenge', table_name='reviews')
    op.create_unique_constraint('uq_review_user_challenge', 'reviews', ['user_id', 'challenge_id'])
    op.create_foreign_key(None, 'reviews', 'users', ['target_user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint('uq_review_user_challenge', 'reviews', type_='unique')
    op.create_index('uq_review_user_target_challenge', 'reviews', ['user_id', 'target_user_id', 'challenge_id'], unique=True)
    op.create_index('idx_reviews_target_user', 'reviews', ['target_user_id'], unique=False)
    op.add_column('refunds', sa.Column('refund_status', mysql.ENUM('pending', 'processing', 'succeeded', 'failed'), nullable=False))
    op.add_column('refunds', sa.Column('amount', mysql.DECIMAL(precision=12, scale=2), nullable=False))
    op.add_column('refunds', sa.Column('toss_refund_id', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('refunds', sa.Column('error_msg', mysql.TEXT(), nullable=True))
    op.add_column('refunds', sa.Column('currency', mysql.VARCHAR(length=3), nullable=False))
    op.add_column('refunds', sa.Column('reason', mysql.VARCHAR(length=100), nullable=False))
    op.drop_constraint(None, 'refunds', type_='foreignkey')
    op.drop_constraint(None, 'refunds', type_='foreignkey')
    op.drop_constraint(None, 'refunds', type_='foreignkey')
    op.create_foreign_key('refunds_ibfk_2', 'refunds', 'challenges', ['challenge_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('refunds_ibfk_1', 'refunds', 'users', ['user_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_refunds_user_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_payment_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_challenge_id'), table_name='refunds')
    op.drop_index('ix_refund_user_date', table_name='refunds')
    op.create_index('uq_refund_toss', 'refunds', ['toss_refund_id'], unique=True)
    op.create_index('ix_refund_user_processed', 'refunds', ['user_id', 'processed_at'], unique=False)
    op.create_index('ix_refund_status', 'refunds', ['refund_status'], unique=False)
    op.create_index('ix_refund_challenge', 'refunds', ['challenge_id'], unique=False)
    op.create_index('ix_refund_amount', 'refunds', ['amount'], unique=False)
    op.alter_column('refunds', 'challenge_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('refunds', 'requested_at')
    op.drop_column('refunds', 'status')
    op.drop_column('refunds', 'refund_reason')
    op.drop_column('refunds', 'refund_amount')
    op.drop_column('refunds', 'payment_id')
    op.add_column('payments', sa.Column('idempotency_key', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('payments', sa.Column('payment_type', mysql.VARCHAR(length=20), nullable=False))
    op.add_column('payments', sa.Column('planner_id_at_payment', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('toss_payment_id', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('payments', sa.Column('currency', mysql.VARCHAR(length=3), nullable=False))
    op.drop_constraint('fk_payment_participation', 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key('payments_ibfk_1', 'payments', 'users', ['user_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('payments_ibfk_2', 'payments', 'challenges', ['challenge_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_challenge_id'), table_name='payments')
    op.drop_index('ix_payment_user_status', table_name='payments')
    op.drop_index('ix_payment_challenge_type', table_name='payments')
    op.create_index('uq_payment_toss', 'payments', ['toss_payment_id'], unique=True)
    op.create_index('uq_payment_idem', 'payments', ['idempotency_key'], unique=True)
    op.create_index('ix_payment_user_created', 'payments', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_payment_status', 'payments', ['status'], unique=False)
    op.create_index('ix_payment_challenge', 'payments', ['challenge_id'], unique=False)
    op.create_index('ix_payment_amount', 'payments', ['amount'], unique=False)
    op.alter_column('payments', 'amount',
               existing_type=sa.Integer(),
               type_=mysql.DECIMAL(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('payments', 'challenge_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('payments', 'metadata_json')
    op.drop_column('payments', 'cancel_reason')
    op.drop_column('payments', 'failure_message')
    op.drop_column('payments', 'failure_code')
    op.drop_column('payments', 'cancelled_at')
    op.drop_column('payments', 'failed_at')
    op.drop_column('payments', 'approved_at')
    op.drop_column('payments', 'requested_at')
    op.drop_column('payments', 'payment_key')
    op.drop_column('payments', 'order_name')
    op.drop_column('payments', 'order_id')
    op.drop_column('payments', 'transaction_type')
    op.drop_column('payments', 'method')
    op.add_column('participations', sa.Column('leave_type', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('participations', sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'participations', type_='foreignkey')
    op.drop_constraint(None, 'participations', type_='foreignkey')
    op.create_foreign_key('participations_ibfk_2', 'participations', 'challenges', ['challenge_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('participations_ibfk_1', 'participations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_participations_status'), table_name='participations')
    op.drop_index(op.f('ix_participations_role'), table_name='participations')
    op.drop_index(op.f('ix_participations_joined_at'), table_name='participations')
    op.drop_index(op.f('ix_participations_is_active'), table_name='participations')
    op.drop_index('ix_participation_status_role', table_name='participations')
    op.drop_index('ix_participation_joined_status', table_name='participations')
    op.create_index('ix_participations_id', 'participations', ['id'], unique=False)
    op.create_index('ix_participation_status', 'participations', ['status'], unique=False)
    op.create_index('ix_participation_role', 'participations', ['role'], unique=False)
    op.create_index('ix_participation_joined', 'participations', ['joined_at'], unique=False)
    op.create_index('ix_participation_active', 'participations', ['is_active'], unique=False)
    op.alter_column('participations', 'joined_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='참가 신청 시간',
               existing_nullable=False)
    op.alter_column('participations', 'status',
               existing_type=sa.Enum('pending', 'payment_pending', 'active', 'paused', 'completed', 'cancelled', 'expelled', 'payment_failed', name='participation_status_enum'),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
    op.add_column('challenges', sa.Column('default_place_id', mysql.VARCHAR(length=64), nullable=True, comment='네이버 placeId (검색/앱 링크용)'))
    op.add_column('challenges', sa.Column('cover_round_picture_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('challenges', sa.Column('reward', mysql.TEXT(), nullable=True, comment='리워드 내용'))
    op.add_column('challenges', sa.Column('participation_fee', mysql.INTEGER(), autoincrement=False, nullable=True, comment='참가비 (원)'))
    op.add_column('challenges', sa.Column('cover_image_url', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('challenges', sa.Column('is_closed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='정산 완료 여부'))
    op.add_column('challenges', sa.Column('default_road_address', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('challenges', sa.Column('fee', mysql.INTEGER(), autoincrement=False, nullable=True, comment='회비 (원)'))
    op.add_column('challenges', sa.Column('max_participation_rate', mysql.INTEGER(), autoincrement=False, nullable=True, comment='최대 참여율 (%)'))
    op.add_column('challenges', sa.Column('default_map_url', mysql.VARCHAR(length=512), nullable=True))
    op.create_foreign_key('challenges_ibfk_3', 'challenges', 'round_pictures', ['cover_round_picture_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_challenges_title'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_status'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_start_date'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_end_date'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_creator_id'), table_name='challenges')
    op.drop_index('ix_challenge_status_date', table_name='challenges')
    op.drop_index('ix_challenge_public', table_name='challenges')
    op.drop_index('ix_challenge_payment_type', table_name='challenges')
    op.drop_index('ix_challenge_participants', table_name='challenges')
    op.drop_index('ix_challenge_creator_status', table_name='challenges')
    op.alter_column('challenges', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('challenges', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('challenges', 'deleted_by',
               existing_type=mysql.INTEGER(),
               comment='삭제한 유저',
               existing_nullable=True)
    op.alter_column('challenges', 'deleted_at',
               existing_type=mysql.DATETIME(),
               comment='삭제 시간',
               existing_nullable=True)
    op.alter_column('challenges', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               comment='삭제 여부')
    op.alter_column('challenges', 'is_public',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('challenges', 'require_approval',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='참가 승인 필요',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('challenges', 'use_reward',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               comment='리워드 사용 여부')
    op.alter_column('challenges', 'same_place_for_all_rounds',
               existing_type=mysql.TINYINT(display_width=1),
               comment='모든 회차 동일 장소 여부',
               existing_nullable=False)
    op.alter_column('challenges', 'default_address',
               existing_type=sa.String(length=300),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('challenges', 'default_place_name',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('challenges', 'min_participation_rate',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment='최소 참여율 (%)',
               existing_comment='%')
    op.alter_column('challenges', 'total_rounds',
               existing_type=mysql.INTEGER(),
               comment='총 회차 수',
               existing_nullable=True)
    op.alter_column('challenges', 'mode',
               existing_type=mysql.ENUM('online', 'offline', 'hybrid'),
               nullable=True)
    op.alter_column('challenges', 'monthly_fee',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment=None,
               existing_comment='원',
               existing_server_default=sa.text("'0'"))
    op.alter_column('challenges', 'entry_fee',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment=None,
               existing_comment='원',
               existing_server_default=sa.text("'0'"))
    op.alter_column('challenges', 'payment_type',
               existing_type=mysql.ENUM('free', 'entry_fee', 'monthly_fee'),
               nullable=True,
               existing_server_default=sa.text("'free'"))
    op.alter_column('challenges', 'max_participants',
               existing_type=mysql.INTEGER(),
               comment='최대 참가자 수',
               existing_nullable=True)
    op.alter_column('challenges', 'min_participants',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment='최소 참가자 수')
    op.alter_column('challenges', 'status',
               existing_type=sa.Enum('draft', 'recruiting', 'active', 'completed', 'cancelled', 'closed', name='challenge_status_enum'),
               type_=mysql.VARCHAR(length=20),
               nullable=True,
               comment='챌린지 상태')
    op.alter_column('challenges', 'title',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.add_column('challenge_rounds', sa.Column('reward_text', mysql.TEXT(), nullable=True, comment='회차 리워드 내용'))
    op.alter_column('challenge_rounds', 'reward_enabled',
               existing_type=mysql.TINYINT(display_width=1),
               comment='리워드 사용 여부',
               existing_comment='보상 활성화 여부',
               existing_nullable=False)
    op.create_table('point_exchange_requests',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('point_amount', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cash_amount', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('status', mysql.ENUM('pending', 'approved', 'rejected', 'paid'), nullable=False),
    sa.Column('requested_at', mysql.DATETIME(), nullable=False),
    sa.Column('processed_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='point_exchange_requests_ibfk_1', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_px_user_requested', 'point_exchange_requests', ['user_id', 'requested_at'], unique=False)
    op.create_index('ix_px_status', 'point_exchange_requests', ['status'], unique=False)
    op.create_index('ix_px_amount', 'point_exchange_requests', ['point_amount'], unique=False)
    op.create_index('ix_point_exchange_requests_id', 'point_exchange_requests', ['id'], unique=False)
<<<<<<< Updated upstream
    op.create_table('email_verifications',
=======
    # (Re)create email_verifications only if missing
    if not inspector.has_table('email_verifications'):
        op.create_table('email_verifications',
>>>>>>> Stashed changes
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('sent_to', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('expires_at', mysql.DATETIME(), nullable=False),
    sa.Column('used_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='email_verifications_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
<<<<<<< Updated upstream
    )
    op.create_index('ix_email_verifications_user_id', 'email_verifications', ['user_id'], unique=False)
=======
        )
    # Ensure a dedicated index exists for user_id (FK)
    idx_names = {i['name'] for i in inspector.get_indexes('email_verifications')}
    if 'ix_email_verifications_user_id' not in idx_names:
        op.create_index('ix_email_verifications_user_id', 'email_verifications', ['user_id'], unique=False)
>>>>>>> Stashed changes
    # ### end Alembic commands ###
