"""update user model with security

Revision ID: 7230f7f48462
Revises: 155f8ce436fa
Create Date: 2025-08-12 09:03:03.952326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7230f7f48462'
down_revision: Union[str, Sequence[str], None] = '155f8ce436fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=30), nullable=False))
    op.add_column('users', sa.Column('identification_number', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('region_living', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('region_active', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('profile_image', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('introduction', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('manner_score', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('total_points', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('penalty_total', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=120),
               nullable=True)
    op.create_index('idx_user_active_points', 'users', ['is_active', 'total_points'], unique=False)
    op.create_index('idx_user_email_active', 'users', ['email', 'is_active'], unique=False)
    op.create_index('idx_user_region_manner', 'users', ['region_active', 'manner_score'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_manner_score'), 'users', ['manner_score'], unique=False)
    op.create_index(op.f('ix_users_region_active'), 'users', ['region_active'], unique=False)
    op.create_index(op.f('ix_users_total_points'), 'users', ['total_points'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_total_points'), table_name='users')
    op.drop_index(op.f('ix_users_region_active'), table_name='users')
    op.drop_index(op.f('ix_users_manner_score'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index('idx_user_region_manner', table_name='users')
    op.drop_index('idx_user_email_active', table_name='users')
    op.drop_index('idx_user_active_points', table_name='users')
    op.alter_column('users', 'email',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=100),
               nullable=False)
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'penalty_total')
    op.drop_column('users', 'total_points')
    op.drop_column('users', 'manner_score')
    op.drop_column('users', 'introduction')
    op.drop_column('users', 'profile_image')
    op.drop_column('users', 'region_active')
    op.drop_column('users', 'region_living')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'identification_number')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
