"""add status to challenge

Revision ID: 7be61cb150bd
Revises: f7fc4dd7c208
Create Date: 2025-08-11 07:48:39.993349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7be61cb150bd'
down_revision: Union[str, Sequence[str], None] = 'f7fc4dd7c208'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenges', sa.Column('status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challenges', 'status')
    # ### end Alembic commands ###
