"""Add report, penalty and chat models

Revision ID: 8c7726b28fa6
Revises: 91bba5e6a6e6
Create Date: 2025-08-12 15:11:47.980528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c7726b28fa6'
down_revision: Union[str, Sequence[str], None] = '91bba5e6a6e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_rooms_id'), 'chat_rooms', ['id'], unique=False)
    op.create_index('ix_chatroom_challenge', 'chat_rooms', ['challenge_id'], unique=False)
    op.create_index('ix_chatroom_created', 'chat_rooms', ['created_at'], unique=False)
    op.create_index('ix_chatroom_creator', 'chat_rooms', ['creator_id'], unique=False)
    op.create_table('penalty_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.Enum('bad_language', 'report', 'frequent_kick', 'frequent_leave', name='penalty_source_enum'), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('given_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_penalty_challenge', 'penalty_histories', ['challenge_id'], unique=False)
    op.create_index('ix_penalty_given_at', 'penalty_histories', ['given_at'], unique=False)
    op.create_index(op.f('ix_penalty_histories_id'), 'penalty_histories', ['id'], unique=False)
    op.create_index('ix_penalty_score', 'penalty_histories', ['score'], unique=False)
    op.create_index('ix_penalty_source', 'penalty_histories', ['source_type'], unique=False)
    op.create_index('ix_penalty_user', 'penalty_histories', ['user_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('reported_id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'under_review', 'resolved', 'rejected', 'cancelled', name='report_status_enum'), nullable=False),
    sa.Column('is_false_report', sa.Boolean(), nullable=False),
    sa.Column('penalty_given', sa.Boolean(), nullable=False),
    sa.Column('penalty_score', sa.Integer(), nullable=False),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reported_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_report_challenge', 'reports', ['challenge_id'], unique=False)
    op.create_index('ix_report_created', 'reports', ['created_at'], unique=False)
    op.create_index('ix_report_reported', 'reports', ['reported_id'], unique=False)
    op.create_index('ix_report_reporter', 'reports', ['reporter_id'], unique=False)
    op.create_index('ix_report_status', 'reports', ['status'], unique=False)
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('file_url', sa.String(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_index('ix_chatmsg_is_read', 'chat_messages', ['is_read'], unique=False)
    op.create_index('ix_chatmsg_room_created', 'chat_messages', ['room_id', 'created_at'], unique=False)
    op.create_index('ix_chatmsg_sender', 'chat_messages', ['sender_id'], unique=False)
    op.create_table('chat_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'user_id', name='uq_chat_participant')
    )
    op.create_index(op.f('ix_chat_participants_id'), 'chat_participants', ['id'], unique=False)
    op.create_index('ix_chatpart_joined', 'chat_participants', ['joined_at'], unique=False)
    op.create_index('ix_chatpart_room', 'chat_participants', ['room_id'], unique=False)
    op.create_index('ix_chatpart_user', 'chat_participants', ['user_id'], unique=False)
    op.create_table('report_proofs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_proofs_id'), 'report_proofs', ['id'], unique=False)
    op.create_index('ix_reportproof_report', 'report_proofs', ['report_id'], unique=False)
    op.create_index('ix_reportproof_uploaded', 'report_proofs', ['uploaded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reportproof_uploaded', table_name='report_proofs')
    op.drop_index('ix_reportproof_report', table_name='report_proofs')
    op.drop_index(op.f('ix_report_proofs_id'), table_name='report_proofs')
    op.drop_table('report_proofs')
    op.drop_index('ix_chatpart_user', table_name='chat_participants')
    op.drop_index('ix_chatpart_room', table_name='chat_participants')
    op.drop_index('ix_chatpart_joined', table_name='chat_participants')
    op.drop_index(op.f('ix_chat_participants_id'), table_name='chat_participants')
    op.drop_table('chat_participants')
    op.drop_index('ix_chatmsg_sender', table_name='chat_messages')
    op.drop_index('ix_chatmsg_room_created', table_name='chat_messages')
    op.drop_index('ix_chatmsg_is_read', table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_index('ix_report_status', table_name='reports')
    op.drop_index('ix_report_reporter', table_name='reports')
    op.drop_index('ix_report_reported', table_name='reports')
    op.drop_index('ix_report_created', table_name='reports')
    op.drop_index('ix_report_challenge', table_name='reports')
    op.drop_table('reports')
    op.drop_index('ix_penalty_user', table_name='penalty_histories')
    op.drop_index('ix_penalty_source', table_name='penalty_histories')
    op.drop_index('ix_penalty_score', table_name='penalty_histories')
    op.drop_index(op.f('ix_penalty_histories_id'), table_name='penalty_histories')
    op.drop_index('ix_penalty_given_at', table_name='penalty_histories')
    op.drop_index('ix_penalty_challenge', table_name='penalty_histories')
    op.drop_table('penalty_histories')
    op.drop_index('ix_chatroom_creator', table_name='chat_rooms')
    op.drop_index('ix_chatroom_created', table_name='chat_rooms')
    op.drop_index('ix_chatroom_challenge', table_name='chat_rooms')
    op.drop_index(op.f('ix_chat_rooms_id'), table_name='chat_rooms')
    op.drop_table('chat_rooms')
    # ### end Alembic commands ###
