"""Initial schema

Revision ID: 91bba5e6a6e6
Revises: 
Create Date: 2025-08-12 15:01:28.434679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91bba5e6a6e6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=255), nullable=False),
    sa.Column('icon_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('embedding_updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag')
    )
    op.create_index('ix_tag_active', 'tags', ['is_active'], unique=False)
    op.create_index('ix_tag_text', 'tags', ['tag'], unique=False)
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('identification_number', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('region_living', sa.String(length=50), nullable=True),
    sa.Column('region_active', sa.String(length=50), nullable=True),
    sa.Column('profile_image', sa.String(length=255), nullable=True),
    sa.Column('introduction', sa.Text(), nullable=True),
    sa.Column('manner_score', sa.Float(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('penalty_total', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_active_points', 'users', ['is_active', 'total_points'], unique=False)
    op.create_index('idx_user_email_active', 'users', ['email', 'is_active'], unique=False)
    op.create_index('idx_user_region_manner', 'users', ['region_active', 'manner_score'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_manner_score'), 'users', ['manner_score'], unique=False)
    op.create_index(op.f('ix_users_region_active'), 'users', ['region_active'], unique=False)
    op.create_index(op.f('ix_users_total_points'), 'users', ['total_points'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('admin_notices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True, comment='작성한 관리자 ID'),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_admin_notice_active', 'admin_notices', ['is_active'], unique=False)
    op.create_index('ix_admin_notice_author', 'admin_notices', ['author_id'], unique=False)
    op.create_index('ix_admin_notice_updated', 'admin_notices', ['updated_at'], unique=False)
    op.create_index(op.f('ix_admin_notices_id'), 'admin_notices', ['id'], unique=False)
    op.create_table('challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('fee', sa.Integer(), nullable=True, comment='회비 (원)'),
    sa.Column('participation_fee', sa.Integer(), nullable=True, comment='참가비 (원)'),
    sa.Column('min_participants', sa.Integer(), nullable=True, comment='최소 참가자 수'),
    sa.Column('max_participants', sa.Integer(), nullable=True, comment='최대 참가자 수'),
    sa.Column('use_reward', sa.Boolean(), nullable=True, comment='리워드 사용 여부'),
    sa.Column('reward', sa.Text(), nullable=True, comment='리워드 내용'),
    sa.Column('total_rounds', sa.Integer(), nullable=True, comment='총 회차 수'),
    sa.Column('min_participation_rate', sa.Integer(), nullable=True, comment='최소 참여율 (%)'),
    sa.Column('is_closed', sa.Boolean(), nullable=True, comment='정산 완료 여부'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='삭제 여부'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시간'),
    sa.Column('deleted_by', sa.Integer(), nullable=True, comment='삭제한 유저'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenges_id'), 'challenges', ['id'], unique=False)
    op.create_table('followings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('following_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'following_id', name='uq_follow_pair')
    )
    op.create_index('ix_follow_created', 'followings', ['created_at'], unique=False)
    op.create_index('ix_follow_follower', 'followings', ['follower_id'], unique=False)
    op.create_index('ix_follow_following', 'followings', ['following_id'], unique=False)
    op.create_index(op.f('ix_followings_id'), 'followings', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('target_type', sa.String(length=30), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('event_type', sa.Enum('challenge_deleted', 'creator_delegated', 'review_created', 'review_updated', 'refund_succeeded', 'refund_failed', 'point_awarded', 'notice_posted', 'join_completed', name='notification_event_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notification_created', 'notifications', ['created_at'], unique=False)
    op.create_index('ix_notification_event', 'notifications', ['event_type'], unique=False)
    op.create_index('ix_notification_is_read', 'notifications', ['is_read'], unique=False)
    op.create_index('ix_notification_target', 'notifications', ['target_type', 'target_id'], unique=False)
    op.create_index('ix_notification_user', 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notification_user_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('point_exchange_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('point_amount', sa.Integer(), nullable=False),
    sa.Column('cash_amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'paid', name='point_exchange_status_enum'), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_point_exchange_requests_id'), 'point_exchange_requests', ['id'], unique=False)
    op.create_index('ix_px_amount', 'point_exchange_requests', ['point_amount'], unique=False)
    op.create_index('ix_px_status', 'point_exchange_requests', ['status'], unique=False)
    op.create_index('ix_px_user_requested', 'point_exchange_requests', ['user_id', 'requested_at'], unique=False)
    op.create_table('user_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('selected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag_id', 'user_id', name='uq_user_tag_pair')
    )
    op.create_index('ix_user_tag_tag', 'user_tags', ['tag_id'], unique=False)
    op.create_index('ix_user_tag_user', 'user_tags', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_tags_id'), 'user_tags', ['id'], unique=False)
    op.create_table('challenge_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_id', 'model_name', name='uq_challenge_embedding_per_model')
    )
    op.create_index(op.f('ix_challenge_embeddings_id'), 'challenge_embeddings', ['id'], unique=False)
    op.create_index('ix_embedding_challenge', 'challenge_embeddings', ['challenge_id'], unique=False)
    op.create_index('ix_embedding_model', 'challenge_embeddings', ['model_name'], unique=False)
    op.create_index('ix_embedding_updated', 'challenge_embeddings', ['updated_at'], unique=False)
    op.create_table('challenge_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.Enum('online', 'offline'), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False, comment='회차 번호(1,2,3,...)'),
    sa.Column('processing_at', sa.Date(), nullable=True, comment='라운드 진행 날짜(YYYY-MM-DD)'),
    sa.Column('start_time', sa.Time(), nullable=True, comment='시작 시간'),
    sa.Column('finish_time', sa.Time(), nullable=True, comment='종료 시간'),
    sa.Column('description', sa.Text(), nullable=True, comment='회차 설명'),
    sa.Column('url', sa.Text(), nullable=True, comment='안내/참고 URL'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True, comment='위도'),
    sa.Column('lon', sa.Float(), nullable=True, comment='경도'),
    sa.Column('geofence_radius_m', sa.Float(), nullable=True, comment='지오펜스 반경 (미터)'),
    sa.Column('zoom_meeting_id', sa.String(length=255), nullable=True, comment='줌 미팅 ID'),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_id', 'round', name='uq_challenge_roundnum'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_challenge_rounds_id'), 'challenge_rounds', ['id'], unique=False)
    op.create_index('ix_round_challenge_round', 'challenge_rounds', ['challenge_id', 'round'], unique=False)
    op.create_index('ix_round_mode', 'challenge_rounds', ['mode'], unique=False)
    op.create_index('ix_round_processing', 'challenge_rounds', ['processing_at'], unique=False)
    op.create_table('challenge_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('selected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag_id', 'challenge_id', name='uq_challenge_tag_pair')
    )
    op.create_index('ix_ch_tag_challenge', 'challenge_tags', ['challenge_id'], unique=False)
    op.create_index('ix_ch_tag_tag', 'challenge_tags', ['tag_id'], unique=False)
    op.create_index(op.f('ix_challenge_tags_id'), 'challenge_tags', ['id'], unique=False)
    op.create_table('invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('inviter_id', sa.Integer(), nullable=False),
    sa.Column('invitee_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'declined', 'canceled', name='invitation_status_enum'), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invitee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_id', 'invitee_id', name='uq_invitation_challenge_invitee')
    )
    op.create_index('ix_invitation_challenge', 'invitations', ['challenge_id'], unique=False)
    op.create_index('ix_invitation_invitee', 'invitations', ['invitee_id'], unique=False)
    op.create_index('ix_invitation_inviter', 'invitations', ['inviter_id'], unique=False)
    op.create_index('ix_invitation_reviewed', 'invitations', ['reviewed_at'], unique=False)
    op.create_index('ix_invitation_status', 'invitations', ['status'], unique=False)
    op.create_index(op.f('ix_invitations_id'), 'invitations', ['id'], unique=False)
    op.create_table('participations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('creator', 'participant', name='participation_role_enum'), nullable=False),
    sa.Column('leave_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'challenge_id', name='uq_participation_user_challenge')
    )
    op.create_index('ix_participation_active', 'participations', ['is_active'], unique=False)
    op.create_index('ix_participation_challenge', 'participations', ['challenge_id'], unique=False)
    op.create_index('ix_participation_joined', 'participations', ['joined_at'], unique=False)
    op.create_index('ix_participation_role', 'participations', ['role'], unique=False)
    op.create_index('ix_participation_status', 'participations', ['status'], unique=False)
    op.create_index('ix_participation_user', 'participations', ['user_id'], unique=False)
    op.create_index(op.f('ix_participations_id'), 'participations', ['id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'cancelled', 'refunded', name='payment_status_enum'), nullable=False),
    sa.Column('toss_payment_id', sa.String(length=100), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('planner_id_at_payment', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_payment_idem'),
    sa.UniqueConstraint('toss_payment_id', name='uq_payment_toss')
    )
    op.create_index('ix_payment_amount', 'payments', ['amount'], unique=False)
    op.create_index('ix_payment_challenge', 'payments', ['challenge_id'], unique=False)
    op.create_index('ix_payment_status', 'payments', ['status'], unique=False)
    op.create_index('ix_payment_user_created', 'payments', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_table('point_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('point_amount', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('gain', 'use', 'refund', name='point_history_type_enum'), nullable=False),
    sa.Column('total_earned_point', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ph_amount', 'point_histories', ['point_amount'], unique=False)
    op.create_index('ix_ph_challenge', 'point_histories', ['challenge_id'], unique=False)
    op.create_index('ix_ph_type', 'point_histories', ['type'], unique=False)
    op.create_index('ix_ph_user_created', 'point_histories', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_point_histories_id'), 'point_histories', ['id'], unique=False)
    op.create_table('refunds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('refund_status', sa.Enum('pending', 'processing', 'succeeded', 'failed', name='refund_status_enum'), nullable=False),
    sa.Column('toss_refund_id', sa.String(length=100), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('toss_refund_id', name='uq_refund_toss')
    )
    op.create_index('ix_refund_amount', 'refunds', ['amount'], unique=False)
    op.create_index('ix_refund_challenge', 'refunds', ['challenge_id'], unique=False)
    op.create_index('ix_refund_status', 'refunds', ['refund_status'], unique=False)
    op.create_index('ix_refund_user_processed', 'refunds', ['user_id', 'processed_at'], unique=False)
    op.create_index(op.f('ix_refunds_id'), 'refunds', ['id'], unique=False)
    op.create_table('proofs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('proof_type', sa.String(length=30), nullable=False),
    sa.Column('file_url', sa.String(length=255), nullable=True),
    sa.Column('exif_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='proof_status_enum'), nullable=False),
    sa.Column('initial_verified_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('ai_score', sa.Float(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('explanation_choices', sa.String(length=255), nullable=True),
    sa.Column('explanation_file_url', sa.String(length=255), nullable=True),
    sa.Column('files_json', sa.JSON(), nullable=True),
    sa.Column('face_compare_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['initial_verified_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['round_id'], ['challenge_rounds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_proof_challenge', 'proofs', ['challenge_id'], unique=False)
    op.create_index('ix_proof_round_user_submitted', 'proofs', ['round_id', 'user_id', 'submitted_at'], unique=False)
    op.create_index('ix_proof_status', 'proofs', ['status'], unique=False)
    op.create_index(op.f('ix_proofs_id'), 'proofs', ['id'], unique=False)
    op.create_table('qrcodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('qr_token', sa.String(length=255), nullable=False),
    sa.Column('scanned_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('jti', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('valid', 'used', 'expired', 'revoked', name='qr_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['challenge_rounds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'round_id', name='uq_qr_user_round')
    )
    op.create_index('ix_qr_round_status', 'qrcodes', ['round_id', 'status'], unique=False)
    op.create_index('ix_qr_token', 'qrcodes', ['qr_token'], unique=False)
    op.create_index('ix_qr_user', 'qrcodes', ['user_id'], unique=False)
    op.create_index(op.f('ix_qrcodes_id'), 'qrcodes', ['id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('helpful_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('visible', 'hidden', 'deleted', name='review_status_enum'), nullable=False),
    sa.Column('images_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['round_id'], ['challenge_rounds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'challenge_id', name='uq_review_user_challenge'),
    sa.UniqueConstraint('user_id', 'round_id', name='uq_review_user_round')
    )
    op.create_index('ix_review_challenge', 'reviews', ['challenge_id'], unique=False)
    op.create_index('ix_review_helpful_count', 'reviews', ['helpful_count'], unique=False)
    op.create_index('ix_review_rating', 'reviews', ['rating'], unique=False)
    op.create_index('ix_review_round', 'reviews', ['round_id'], unique=False)
    op.create_index('ix_review_status', 'reviews', ['status'], unique=False)
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_table('round_pictures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('file_url', sa.String(length=255), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['challenge_rounds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_round_pictures_id'), 'round_pictures', ['id'], unique=False)
    op.create_index('ix_roundpic_created', 'round_pictures', ['created_at'], unique=False)
    op.create_index('ix_roundpic_public', 'round_pictures', ['is_public'], unique=False)
    op.create_index('ix_roundpic_round', 'round_pictures', ['round_id'], unique=False)
    op.create_index('ix_roundpic_uploader', 'round_pictures', ['uploaded_by'], unique=False)
    op.create_table('review_helpfuls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id', 'user_id', name='uq_helpful_review_user')
    )
    op.create_index('ix_helpful_created', 'review_helpfuls', ['created_at'], unique=False)
    op.create_index('ix_helpful_review', 'review_helpfuls', ['review_id'], unique=False)
    op.create_index('ix_helpful_user', 'review_helpfuls', ['user_id'], unique=False)
    op.create_index(op.f('ix_review_helpfuls_id'), 'review_helpfuls', ['id'], unique=False)
    op.create_table('round_attendances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('is_checked_in', sa.Boolean(), nullable=False),
    sa.Column('is_checked_out', sa.Boolean(), nullable=False),
    sa.Column('checkin_time', sa.DateTime(), nullable=True),
    sa.Column('checkout_time', sa.DateTime(), nullable=True),
    sa.Column('manually_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('ai_score', sa.Float(), nullable=True),
    sa.Column('qr_id', sa.Integer(), nullable=True),
    sa.Column('scanned_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'present', 'late', 'absent', 'rejected', name='attendance_status_enum'), nullable=False),
    sa.Column('proof_id', sa.Integer(), nullable=True),
    sa.Column('verified_by_meta', sa.Boolean(), nullable=False),
    sa.Column('meta_check_time', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('check_method', sa.Enum('qr', 'gps', 'image', 'manual', name='check_method_enum'), nullable=False),
    sa.Column('auto_decision', sa.Enum('_pass', 'review', 'fail', name='auto_decision_enum'), nullable=True),
    sa.Column('initial_decision', sa.Enum('approved', 'rejected', 'review', name='initial_decision_enum'), nullable=False),
    sa.Column('initial_decision_reason', sa.Text(), nullable=True),
    sa.Column('initial_decision_code', sa.Enum('late', 'no_gps', 'wrong_place', 'no_face', 'file_invalid', 'other', name='initial_decision_code_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['proof_id'], ['proofs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['qr_id'], ['qrcodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['round_id'], ['challenge_rounds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'round_id', name='uq_ra_user_round')
    )
    op.create_index('ix_ra_checkin', 'round_attendances', ['checkin_time'], unique=False)
    op.create_index('ix_ra_round_user', 'round_attendances', ['round_id', 'user_id'], unique=False)
    op.create_index('ix_ra_status', 'round_attendances', ['status'], unique=False)
    op.create_index(op.f('ix_round_attendances_id'), 'round_attendances', ['id'], unique=False)
    op.create_table('appeals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_attendance_id', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('files_url', sa.JSON(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('appeal_status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('decision_code', sa.Enum('insufficient_evidence', 'still_no_gps', 'time_mismatch', 'face_mismatch', 'duplicate', 'other', name='appeal_decision_code_enum'), nullable=True),
    sa.Column('auto_reason', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['round_attendance_id'], ['round_attendances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_appeal_ra', 'appeals', ['round_attendance_id'], unique=False)
    op.create_index('ix_appeal_status', 'appeals', ['appeal_status'], unique=False)
    op.create_index('ix_appeal_submitted', 'appeals', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_appeals_id'), 'appeals', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appeals_id'), table_name='appeals')
    op.drop_index('ix_appeal_submitted', table_name='appeals')
    op.drop_index('ix_appeal_status', table_name='appeals')
    op.drop_index('ix_appeal_ra', table_name='appeals')
    op.drop_table('appeals')
    op.drop_index(op.f('ix_round_attendances_id'), table_name='round_attendances')
    op.drop_index('ix_ra_status', table_name='round_attendances')
    op.drop_index('ix_ra_round_user', table_name='round_attendances')
    op.drop_index('ix_ra_checkin', table_name='round_attendances')
    op.drop_table('round_attendances')
    op.drop_index(op.f('ix_review_helpfuls_id'), table_name='review_helpfuls')
    op.drop_index('ix_helpful_user', table_name='review_helpfuls')
    op.drop_index('ix_helpful_review', table_name='review_helpfuls')
    op.drop_index('ix_helpful_created', table_name='review_helpfuls')
    op.drop_table('review_helpfuls')
    op.drop_index('ix_roundpic_uploader', table_name='round_pictures')
    op.drop_index('ix_roundpic_round', table_name='round_pictures')
    op.drop_index('ix_roundpic_public', table_name='round_pictures')
    op.drop_index('ix_roundpic_created', table_name='round_pictures')
    op.drop_index(op.f('ix_round_pictures_id'), table_name='round_pictures')
    op.drop_table('round_pictures')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_index('ix_review_status', table_name='reviews')
    op.drop_index('ix_review_round', table_name='reviews')
    op.drop_index('ix_review_rating', table_name='reviews')
    op.drop_index('ix_review_helpful_count', table_name='reviews')
    op.drop_index('ix_review_challenge', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_qrcodes_id'), table_name='qrcodes')
    op.drop_index('ix_qr_user', table_name='qrcodes')
    op.drop_index('ix_qr_token', table_name='qrcodes')
    op.drop_index('ix_qr_round_status', table_name='qrcodes')
    op.drop_table('qrcodes')
    op.drop_index(op.f('ix_proofs_id'), table_name='proofs')
    op.drop_index('ix_proof_status', table_name='proofs')
    op.drop_index('ix_proof_round_user_submitted', table_name='proofs')
    op.drop_index('ix_proof_challenge', table_name='proofs')
    op.drop_table('proofs')
    op.drop_index(op.f('ix_refunds_id'), table_name='refunds')
    op.drop_index('ix_refund_user_processed', table_name='refunds')
    op.drop_index('ix_refund_status', table_name='refunds')
    op.drop_index('ix_refund_challenge', table_name='refunds')
    op.drop_index('ix_refund_amount', table_name='refunds')
    op.drop_table('refunds')
    op.drop_index(op.f('ix_point_histories_id'), table_name='point_histories')
    op.drop_index('ix_ph_user_created', table_name='point_histories')
    op.drop_index('ix_ph_type', table_name='point_histories')
    op.drop_index('ix_ph_challenge', table_name='point_histories')
    op.drop_index('ix_ph_amount', table_name='point_histories')
    op.drop_table('point_histories')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index('ix_payment_user_created', table_name='payments')
    op.drop_index('ix_payment_status', table_name='payments')
    op.drop_index('ix_payment_challenge', table_name='payments')
    op.drop_index('ix_payment_amount', table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_participations_id'), table_name='participations')
    op.drop_index('ix_participation_user', table_name='participations')
    op.drop_index('ix_participation_status', table_name='participations')
    op.drop_index('ix_participation_role', table_name='participations')
    op.drop_index('ix_participation_joined', table_name='participations')
    op.drop_index('ix_participation_challenge', table_name='participations')
    op.drop_index('ix_participation_active', table_name='participations')
    op.drop_table('participations')
    op.drop_index(op.f('ix_invitations_id'), table_name='invitations')
    op.drop_index('ix_invitation_status', table_name='invitations')
    op.drop_index('ix_invitation_reviewed', table_name='invitations')
    op.drop_index('ix_invitation_inviter', table_name='invitations')
    op.drop_index('ix_invitation_invitee', table_name='invitations')
    op.drop_index('ix_invitation_challenge', table_name='invitations')
    op.drop_table('invitations')
    op.drop_index(op.f('ix_challenge_tags_id'), table_name='challenge_tags')
    op.drop_index('ix_ch_tag_tag', table_name='challenge_tags')
    op.drop_index('ix_ch_tag_challenge', table_name='challenge_tags')
    op.drop_table('challenge_tags')
    op.drop_index('ix_round_processing', table_name='challenge_rounds')
    op.drop_index('ix_round_mode', table_name='challenge_rounds')
    op.drop_index('ix_round_challenge_round', table_name='challenge_rounds')
    op.drop_index(op.f('ix_challenge_rounds_id'), table_name='challenge_rounds')
    op.drop_table('challenge_rounds')
    op.drop_index('ix_embedding_updated', table_name='challenge_embeddings')
    op.drop_index('ix_embedding_model', table_name='challenge_embeddings')
    op.drop_index('ix_embedding_challenge', table_name='challenge_embeddings')
    op.drop_index(op.f('ix_challenge_embeddings_id'), table_name='challenge_embeddings')
    op.drop_table('challenge_embeddings')
    op.drop_index(op.f('ix_user_tags_id'), table_name='user_tags')
    op.drop_index('ix_user_tag_user', table_name='user_tags')
    op.drop_index('ix_user_tag_tag', table_name='user_tags')
    op.drop_table('user_tags')
    op.drop_index('ix_px_user_requested', table_name='point_exchange_requests')
    op.drop_index('ix_px_status', table_name='point_exchange_requests')
    op.drop_index('ix_px_amount', table_name='point_exchange_requests')
    op.drop_index(op.f('ix_point_exchange_requests_id'), table_name='point_exchange_requests')
    op.drop_table('point_exchange_requests')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index('ix_notification_user_read', table_name='notifications')
    op.drop_index('ix_notification_user', table_name='notifications')
    op.drop_index('ix_notification_target', table_name='notifications')
    op.drop_index('ix_notification_is_read', table_name='notifications')
    op.drop_index('ix_notification_event', table_name='notifications')
    op.drop_index('ix_notification_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_followings_id'), table_name='followings')
    op.drop_index('ix_follow_following', table_name='followings')
    op.drop_index('ix_follow_follower', table_name='followings')
    op.drop_index('ix_follow_created', table_name='followings')
    op.drop_table('followings')
    op.drop_index(op.f('ix_challenges_id'), table_name='challenges')
    op.drop_table('challenges')
    op.drop_index(op.f('ix_admin_notices_id'), table_name='admin_notices')
    op.drop_index('ix_admin_notice_updated', table_name='admin_notices')
    op.drop_index('ix_admin_notice_author', table_name='admin_notices')
    op.drop_index('ix_admin_notice_active', table_name='admin_notices')
    op.drop_table('admin_notices')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_total_points'), table_name='users')
    op.drop_index(op.f('ix_users_region_active'), table_name='users')
    op.drop_index(op.f('ix_users_manner_score'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_user_region_manner', table_name='users')
    op.drop_index('idx_user_email_active', table_name='users')
    op.drop_index('idx_user_active_points', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_index('ix_tag_text', table_name='tags')
    op.drop_index('ix_tag_active', table_name='tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
