"""아

Revision ID: 94d45affbe4e
Revises: d260b37a7a41
Create Date: 2025-08-26 08:09:35.374693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94d45affbe4e'
down_revision: Union[str, Sequence[str], None] = 'd260b37a7a41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email_verified', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_is_active', table_name='users')
    op.drop_index('ix_users_manner_score', table_name='users')
    op.drop_index('ix_users_phone', table_name='users')
    op.drop_index('ix_users_total_points', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_total_points', 'users', ['total_points'], unique=False)
    op.create_index('ix_users_phone', 'users', ['phone'], unique=True)
    op.create_index('ix_users_manner_score', 'users', ['manner_score'], unique=False)
    op.create_index('ix_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email_verified', 'users', ['email_verified'], unique=False)
    # ### end Alembic commands ###
