"""challenge: cover/default place cols + enum defaults

Revision ID: b53dd17c0d32
Revises: dee8cc163b63
Create Date: 2025-09-01 23:10:06.472674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b53dd17c0d32'
down_revision: Union[str, Sequence[str], None] = 'dee8cc163b63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('challenges', 'status',
               existing_type=mysql.ENUM('recruiting', 'active', 'completed', 'cancelled'),
               type_=sa.String(length=20),
               existing_comment='챌린지 상태',
               existing_nullable=True,
               existing_server_default=sa.text("'recruiting'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('challenges', 'status',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('recruiting', 'active', 'completed', 'cancelled'),
               existing_comment='챌린지 상태',
               existing_nullable=True,
               existing_server_default=sa.text("'recruiting'"))
    # ### end Alembic commands ###
