"""update models

Revision ID: bc30b4dc9471
Revises: 7be61cb150bd
Create Date: 2025-08-12 07:10:56.716480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bc30b4dc9471'
down_revision: Union[str, Sequence[str], None] = '7be61cb150bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenge_participants', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('challenge_participants', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('challenge_participants', sa.Column('role', sa.Enum('planner', 'participant'), nullable=True))
    op.add_column('challenge_participants', sa.Column('leave_type', sa.String(length=20), nullable=True))
    op.drop_index('ix_challenge_participants_participant_id', table_name='challenge_participants')
    op.create_index(op.f('ix_challenge_participants_id'), 'challenge_participants', ['id'], unique=False)
    op.drop_column('challenge_participants', 'participant_id')
    op.add_column('challenges', sa.Column('fee', sa.Integer(), nullable=True, comment='회비 (원)'))
    op.add_column('challenges', sa.Column('participation_fee', sa.Integer(), nullable=True, comment='참가비 (원)'))
    op.add_column('challenges', sa.Column('min_participants', sa.Integer(), nullable=True, comment='최소 참가자 수'))
    op.add_column('challenges', sa.Column('max_participants', sa.Integer(), nullable=True, comment='최대 참가자 수'))
    op.add_column('challenges', sa.Column('use_reward', sa.Boolean(), nullable=True, comment='리워드 사용 여부'))
    op.add_column('challenges', sa.Column('reward', sa.Text(), nullable=True, comment='리워드 내용'))
    op.add_column('challenges', sa.Column('total_rounds', sa.Integer(), nullable=True, comment='총 회차 수'))
    op.add_column('challenges', sa.Column('min_participation_rate', sa.Integer(), nullable=True, comment='최소 참여율 (%)'))
    op.add_column('challenges', sa.Column('is_closed', sa.Boolean(), nullable=True, comment='정산 완료 여부'))
    op.add_column('challenges', sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='삭제 여부'))
    op.add_column('challenges', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시간'))
    op.add_column('challenges', sa.Column('deleted_by', sa.Integer(), nullable=True, comment='삭제한 유저'))
    op.create_foreign_key(None, 'challenges', 'users', ['deleted_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'challenges', type_='foreignkey')
    op.drop_column('challenges', 'deleted_by')
    op.drop_column('challenges', 'deleted_at')
    op.drop_column('challenges', 'is_deleted')
    op.drop_column('challenges', 'is_closed')
    op.drop_column('challenges', 'min_participation_rate')
    op.drop_column('challenges', 'total_rounds')
    op.drop_column('challenges', 'reward')
    op.drop_column('challenges', 'use_reward')
    op.drop_column('challenges', 'max_participants')
    op.drop_column('challenges', 'min_participants')
    op.drop_column('challenges', 'participation_fee')
    op.drop_column('challenges', 'fee')
    op.add_column('challenge_participants', sa.Column('participant_id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_challenge_participants_id'), table_name='challenge_participants')
    op.create_index('ix_challenge_participants_participant_id', 'challenge_participants', ['participant_id'], unique=False)
    op.drop_column('challenge_participants', 'leave_type')
    op.drop_column('challenge_participants', 'role')
    op.drop_column('challenge_participants', 'is_active')
    op.drop_column('challenge_participants', 'id')
    # ### end Alembic commands ###
