"""fix foreign key references

Revision ID: cfadd27c1684
Revises: 4b11e1acd33e
Create Date: 2025-08-12 13:28:03.807703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfadd27c1684'
down_revision: Union[str, Sequence[str], None] = '4b11e1acd33e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('round_picture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challengeround_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('file_url', sa.String(length=255), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['challengeround_id'], ['challenge_rounds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_roundpic_public', 'round_picture', ['is_public'], unique=False)
    op.create_index('ix_roundpic_round', 'round_picture', ['challengeround_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_roundpic_round', table_name='round_picture')
    op.drop_index('ix_roundpic_public', table_name='round_picture')
    op.drop_table('round_picture')
    # ### end Alembic commands ###
