"""add tag & user_tag & challenge_tag

Revision ID: dd6bdf057ac0
Revises: 69705fbb2a83
Create Date: 2025-08-19 01:48:17.801016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd6bdf057ac0'
down_revision: Union[str, Sequence[str], None] = 'add_report_auto_eval_20250905'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_round_manager_challenge'), table_name='round_managers')
    # op.drop_index(op.f('ix_round_manager_round'), table_name='round_managers')
    # op.drop_index(op.f('ix_round_manager_user'), table_name='round_managers')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_round_manager_user'), 'round_managers', ['user_id'], unique=False)
    op.create_index(op.f('ix_round_manager_round'), 'round_managers', ['round_id'], unique=False)
    op.create_index(op.f('ix_round_manager_challenge'), 'round_managers', ['challenge_id'], unique=False)
    # ### end Alembic commands ###
