"""add new field2

Revision ID: f7fc4dd7c208
Revises: f28c03a7c9a0
Create Date: 2025-08-11 05:44:11.198532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f7fc4dd7c208'
down_revision: Union[str, Sequence[str], None] = 'f28c03a7c9a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenge_participants',
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('participant_id')
    )
    op.create_index(op.f('ix_challenge_participants_participant_id'), 'challenge_participants', ['participant_id'], unique=False)
    op.add_column('challenges', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('challenges', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.add_column('challenges', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('challenges', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('challenges', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('challenges', 'title',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_index('ix_challenges_title', table_name='challenges')
    op.create_foreign_key(None, 'challenges', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'challenges', type_='foreignkey')
    op.create_index('ix_challenges_title', 'challenges', ['title'], unique=True)
    op.alter_column('challenges', 'title',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('challenges', 'created_at')
    op.drop_column('challenges', 'end_date')
    op.drop_column('challenges', 'start_date')
    op.drop_column('challenges', 'creator_id')
    op.drop_column('challenges', 'description')
    op.drop_index(op.f('ix_challenge_participants_participant_id'), table_name='challenge_participants')
    op.drop_table('challenge_participants')
    # ### end Alembic commands ###
