"""add email_verifications table & simplify user phone/id columns

Revision ID: fb6588186940
Revises: 51aeb541d913
Create Date: 2025-08-27 06:45:18.227994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fb6588186940'
down_revision: Union[str, Sequence[str], None] = '51aeb541d913'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('challenges', 'start_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('challenges', 'end_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('challenges', 'status',
               existing_type=mysql.VARCHAR(length=20),
               comment='챌린지 상태',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('challenges', 'status',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='챌린지 상태',
               existing_nullable=True)
    op.alter_column('challenges', 'end_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('challenges', 'start_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
